### ISSUE TITLE
task exceptions are not handled for periodic tasks in eager mode

### ISSUE THREAD

**Issue by iivvoo** [coleifer/huey#171]
The huey consumer doesn't handle exceptions on tasks if huey is configed to run always_eager=True
This results in the worker process/thread dying and no longer scheduling any tasks:

The following simple setup:

```
# main.py
from huey import RedisHuey
huey = RedisHuey(always_eager=True)

@huey.periodic_task(crontab(minute='*'))
def print_time():
    print("Time!")
    print(datetime.now())

@huey.periodic_task(crontab(minute='*'))
def keep_on_running():
    print("Running...")
```

When invoked with bin/huey_consumer main.huey will result in

```
Exception in thread Scheduler:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "(..path..)/huey-test/lib/python3.5/site-packages/huey/consumer.py", line 352, in _run
    consumer_process.loop()
  File "(..path..)/huey-test/lib/python3.5/site-packages/huey/consumer.py", line 239, in loop
    self.enqueue(task)
  File "(..path..)/huey-test/lib/python3.5/site-packages/huey/consumer.py", line 71, in enqueue
    self.huey.enqueue(task)
  File "(..path..)/huey-test/lib/python3.5/site-packages/huey/api.py", line 215, in enqueue
    return task.execute()
  File "(..path..)/huey-test/lib/python3.5/site-packages/huey/api.py", line 550, in execute
    return func(*args, **kwargs)
  File "(..path..)/huey-test/main.py", line 8, in print_time
    print(datetime.now())
AttributeError: module 'datetime' has no attribute 'now'
```

It might seem not to make sense to execute tasks eagerly *and* run a consumer, but the consumer is still required for periodic tasks and in development it's nice to have immediate execution and not always a requirement to run the consumer.

The fix might be to never run a consumer in eager mode - it doesn't make sense.

**Comment by coleifer** [comment]
Running the consumer with `always_eager=True` is definitely not a use-case I had ever considered. If you're running your periodic tasks in a consumer anyways, why not let the consumer run your regular tasks as well? I guess, to me, the whole point of `always_eager` was to allow for testing and development *without* the need for a separate consumer + message queue process + etc.

I'm not sure how familiar you are with the consumer internals, but inside the consumer is a thread (or process or greenlet, depending on your chosen execution model) called the Scheduler that does two things:

1. Every minute it checks to see if any periodic tasks should be run, and if so, **enqueues** them into the work queue.
2. Continually checks its list of tasks that were scheduled to run in the future, and **enqueues** any tasks whose due-date is not longer in the future and is thus eligible for execution.

The key word in both cases is **enqueues**.

When `always_eager` is True and a task is enqueued, instead of putting it on a queue, Huey executes the task right then and there and returns you whatever the task returned (skipping redis and the result store in the process).

This has an interesting consequence, which is that you **cannot** schedule tasks for future execution when `always_eager=True`. For instance, if `always_eager` is True, then the following code will run immediately as opposed to an hour in the future:

```python
my_task.schedule(args=('foo', 'bar'), delay=3600)
```

It runs immediately because `always_eager` is designed for testing and is synchronous. To make the delay work we'd need to be running the consumer or a the least a lightweight thread that acted like the a scheduler.

I think there are two ways this could go:

1. When always_eager is True, allow tasks to be scheduled in the future, and make it clear to the user that these future-scheduled always-eager tasks will not run unless the consumeris running. Additionally, re-use the error-handling code from the consumer's worker threads to make sure the scheduler doesn't blow up if it encounters a misbehaved periodic/scheduled task.
2. Do not allow the consumer to be run if `always_eager` is true.

I think the second choice is the correct one. It's the easiest to understand, and it will make it very obvious to anyone using Huey if they deploy an application but accidentally have `always_eager` turned on.

**Comment by coleifer** [comment]
An exception is now raised if you attempt to run the consumer with `always_eager=True`.
