### ISSUE TITLE
huey is behaving asynchronous when DEBUG = True in Django

### ISSUE THREAD

**Issue by angvp** [coleifer/huey#176]
Hi, I figured out that changing that setting made huey to work asynchronous as expected, but I imagine this is a bug and not the desired behaviour, right?

**Comment by coleifer** [comment]
Can you please tell me a bit more?

Do you mean that when `settings.DEBUG = True`, and you call a task, it is not being run immediately?

**Comment by angvp** [comment]
Yes, when settings.DEBUG = True I call a task is being run immediately on the request .. and yes, the consumer is running with DEBUG = True

**Comment by coleifer** [comment]
Sorry, I do not understand. Can you please tell me exactly what settings you're using, what you're running, and what you think is not doing the right thing?

I can't tell from your reply whether the task is running in-process or being executed by the consumer.

**Comment by angvp** [comment]
Hello @coleifer !

Let me try to explain this better:

I have a django project, I have an app, and I have several views there.

I needed to run some tasks asynchronous while one of these views are being executed, so I choose to use huey, then I've created a task on tasks.py and called that task from one of my views. 

That task runs in 30 seconds~, so I want to give a response to the view w/o being blocked by that task, huey does that fine but I found when I'm having in my settings the variable DEBUG in True (for dev purposes) and then I call the view, and the view call, the task is not being executed asynchronous, so I have to wait those 30~ seconds on the view. 

It's clearer now or you need some code? to see it?

**Comment by coleifer** [comment]
Thanks for the info, that definitely clarifies the issue. I could have sworn this was documented but it was not, so I've created a new docs section. What it amounts to is that ``huey`` explicitly sets "always_eager = True" when ``DEBUG=True``, because most dev/test environments do not want to run both Redis and a consumer process.

Does this clear things up?  http://huey.readthedocs.io/en/latest/django.html#debug-and-synchronous-execution
