### ISSUE TITLE
Get task by UID

### ISSUE THREAD

**Issue by felipe3dfx** [coleifer/huey#178]
I need get a task by UID, I tried to get it with HUEY.result('my_uid'), but always is None:

```
location_delivery_dict.update({
    'update_task_id': update_task_id.task.task_id,
    'email_task_id': email_task_id.task.task_id,
})
cache.set(cache_key, location_delivery_dict, timeout=None)

if cache.get(cache_key) is not None:
    cache_location_tasks = cache.get(cache_key)
    if cache_location_tasks.get('id') == instance.id:
        task_update = HUEY.result(
            cache_location_tasks.get('update_task_id')
        )
        task_email = HUEY.result(
            cache_location_tasks.get('email_task_id')
        )
        if task_update or task_email:
            task_update.revoke()
            task_email.revoke()
```

Im using Django 1.10 and Huey 1.20

**Comment by coleifer** [comment]
`Huey.result` method is covered by test-cases and works correctly in my opinion. You can fire up the simple example included in the huey repo and verify for yourself:

```ipython
In [1]: from main import *

In [2]: count_beans(100)
Out[2]: <huey.api.TaskResultWrapper at 0x7f68ac5fa350>

In [3]: r = _

In [4]: r.task.task_id
Out[4]: 'd924b9cc-0033-4def-a051-3c4c54cb61d1'

In [5]: tid = r.task.task_id

In [6]: huey.result(tid)
Out[6]: 'Counted 100 beans'
```

So my guess is that the tasks you're attempting to work on are periodic tasks... If that's the case, then Huey will not store any return values for them.

For one, since periodic tasks are not invoked by the end-user, the task id should theoretically be unavailable. It's an implementation detail that, in fact, the task ID for periodic tasks is always the same...but from an API perspective, you shouldn't be able to access it.

Can you clarify your use-case and what's going on in the code you pasted?

**Comment by felipe3dfx** [comment]
I want to set in cache the task_id, the tasks are schedule with a delay:

```
update_task_id = update_delivery_minutes_change.schedule(
    args=(instance.id,),
    delay=(60 * 30)
)
```

so, i want get the uid from cache and know if the task was ended, if not, i revoke for create a new task

but the result always is None, in console i can see the task is queueing.

**Comment by felipe3dfx** [comment]
I use HUEY.scheduled() but when i tried revoke the task nothing happen,

```
update_task_id = cache_location_tasks.get('update_task_id')
    email_task_id = cache_location_tasks.get('email_task_id')
    for event in HUEY.scheduled():
        if event.task_id in [update_task_id, email_task_id]:
            HUEY.revoke(event)
```
is it the correct way to revoke a task?

**Comment by felipe3dfx** [comment]
The revoke function works fine, but is confusing when is revoked a task its return is None
Thanks
