### ISSUE TITLE
How can i write unit test for huey scheduled task?

### ISSUE THREAD

**Issue by felipe3dfx** [coleifer/huey#179]
Im writing unit test for schedule task, but the task_id return always None, How can i mock or emulate the task for create a test case?

**Comment by coleifer** [comment]
I'm not sure what you want to test. That the task is scheduled? The task logic itself?

**Comment by felipe3dfx** [comment]
i want test that the task is scheduled and schedule method return a task, with the task id i will save it in cache for ask it later for it and schedule it egain the task

**Comment by coleifer** [comment]
Well, huey the library already tests that when you schedule a task it goes in the schedule, but of course it's good to have integration tests.

I don't think you are talking about unit tests at all, though, rather integration tests since you seem to want to involve many components of the system including libraries.

I'd suggest hitting up stackoverflow as I don't intend to give advice on these types of things on GitHub.
