### ISSUE TITLE
Task and periodic_task decorator for the same function

### ISSUE THREAD

**Issue by Gystark** [coleifer/huey#186]
Hi,

First of all thank you for this wonderful project ! It seems that decorating a function with both task and periodic_task results in Huey not picking it up when called in a Django view (always_eager is set to false). If  I only decorate the same function with either task or periodic_task, it runs in the desired  way and the same goes for db_task and db_periodic_task.
Is there a way to have the same function as a task and a periodic task at the same time with Huey?

Thanks in advance!

**Comment by coleifer** [comment]
That's a pretty interesting question, let me think about it!

**Comment by coleifer** [comment]
Hmm, you know, I think the answer will be "no", simply because when you decorate a function with "@huey.task" the function calls are magically turned into queued function invocations. How would one differentiate intent when calling a function that is wrapped by both @task and @periodic_task?

Why not just do this:

```python
def my_function():
    pass

@huey.task()
def my_task():
    return my_function()

@huey.periodic_task(...)
def my_periodic_task():
    my_function()
```

**Comment by Gystark** [comment]
Thanks for the quick reply, the solution you have suggested should have come to my mind days ago.
