### ISSUE TITLE
Issue with stopping a running task

### ISSUE THREAD

**Issue by vladlep** [coleifer/huey#194]
Hello,

We are running huey==0.4.8 with django for a while and we are very happy with it. But now we had an issues and don't know how to fix it. We made a periodic task to calculate some user statistics and forward them to mixpanel for display. 

    @db_periodic_task(crontab(hour=11, minute=30))
    def stats_task():

This task is one that actually passes through 25k users and calculates properties of them, which makes it quite intensive for memory and cpu. The problem is that the task blocks our production server once it starts. It hits 100% cpu and it gets stuck there (there are no more writes or network comm). 

Therefore i have some questions:
1. How do i stop it? Right now in order to stop it I have to restart the server and then server is unblocked.  I also removed the code of the task and restarted huey. 
The problem is that the start restarts after a while (somehow random times). Until now it restarted 3 times after around 3 hours 12 hours and now after 24 hours (i might be a bit wrong with these times).

I imagine that the task is still stored in redis although i removed the code and is restarting because it  was interrupted before it finished. Still, i would like to flush it.

2. How can I make this task run with limiting the cpu usage and memory
I am looking into this and though of limiting the memory for redis and choosing for an ALU policy. That gave me errors on other tasks:
```

ResponseError: OOM command not allowed when used memory > 'maxmemory'.
huey/utils.py in wrap_exception at line 18
    mod = sys.modules[path]
    return getattr(mod, klass)
def wrap_exception(new_exc_class):
    exc_class, exc, tb = sys.exc_info()
    raise new_exc_class('%s: %s' % (exc_class.__name__, exc))
def local_to_utc(dt):
    return datetime.datetime(*time.gmtime(time.mktime(dt.timetuple()))[:6])
```
and
```
Error enqueueing task: <invoices.tasks.queuecmd_recurrent_invoice_send_periodic_task object at 0x7f8319b92050>
```
I could not figure out how to limit the CPU usage. Also when trying to replicate this on another server, it was working since the cpu went only up to 75%. But that server is from digital ocean not linode plus has a few different configurations. 

Considered upgrading huey to a newer version but not sure if that will have any benefits or if it will break anything.

Any suggestions or opinions would be great.

Thanks
Vlad

**Comment by coleifer** [comment]
> I imagine that the task is still stored in redis although i removed the code and is restarting because it was interrupted before it finished. Still, i would like to flush it.

That is not how huey works. If the process running the queue consumer sees the task, then it will execute it (providing it has not been revoked). There's no way something could be persisted in redis that would somehow allow the task to mysteriously/randomly execute.

Regarding the CPU usage - Python is effectively single-threaded, due to the global interpreter lock. It can peg a single CPU but unless you have multiple interpreter processes running you'll only ever be maxing out one core. If your server, too, is single-core, I suppose you could run into trouble but then the question would be why are you running a single-core server?

> How do i stop it?

Kill the process? No idea. huey does not contain any logic to handle killing tasks.

--------------

At any rate, I do not believe this is a bug with Huey, and any questions about systems administration are so beyond the scope of this issue tracker that I won't venture any guesses.

**Comment by vladlep** [comment]
Hi thanks for the ideas. I agree that it might not be a huey issue but i still have a feeling a huey config or something regarding heuy-redis is the key to fixing this.  We are running a  multiple core server.

I do not know the exact implementation of huey but there is a persistence of task from my understanding, in case of whatever (server fails, power is down ...etc).

I am looking at these links and trying to figure out:
http://abhinavsingh.com/customizing-redis-pubsub-for-message-persistence-part-2/
http://stackoverflow.com/questions/7149074/deleting-all-pending-tasks-in-celery-rabbitmq

Anyways, I will find a solution in the end but was just trying my luck in case someone had a great idea. 

Thanks,
Vlad
