### ISSUE TITLE
[QUESTION] Running multiple consumers

### ISSUE THREAD

**Issue by rstuart85** [coleifer/huey#195]
Hi,

I couldn't find a mailing list or a chat channel to ask this question so I decided to create an issue. Apologies if this isn't the right place for this.

I'm looking for a replacement for Celery. We run in Kubernetes in production with pretty small nodes so instead of controlling the number of workers via a consumer, instead we'd like to create a bunch of single worker consumers and let Kubernetes distribute them across nodes. Is Huey designed to work this way? I experimented locally with multiple consumers and it appears that one consumer gets scheduled all jobs. This appears to due to the backoff param and the jobs being short lived.

So, here is a specific question: If I have long running jobs, will a consumer greedily fetch jobs off the queue, or will another consumer pick-up the job? Put another way, if all workers are busy, will a consumer still pull jobs off the queue similar to the pre-fetch in Celery?

Thanks in advanced.

**Comment by coleifer** [comment]
Consumers will not greedily pull jobs from the queue, it should be safe to run multiple consumers though I haven't done this myself so am unaware of any potential edge cases. One thing to note is that you will want to ensure that only one consumer is running with the flag for periodic tasks, otherwise every consumer will enqueue a copy of the periodic task (periodic tasks being the crontab functionality).

**Comment by rstuart85** [comment]
Interesting. So if the volume of periodic tasks becomes too much then your only choice is to scale the consumer with the -w option. I'll keep that in mind.

**Comment by coleifer** [comment]
I don't think you're following. If you're using huey's crontab functionality, then it's important to understand that each consumer you run will enqueue a ln instance of your crib task at the appropriate time. This is most likely not what you want: you'll only want one instance of the crib job to run as opposed to *n* (one for each consumer master process). To avoid the issue, just run all consumers but one with periodic tasks disabled.

**Comment by rstuart85** [comment]
I understand. My point is when you are relying on something like Kubernetes to do scaling rather than the -w option to a consumer, you are going to be limited on the bandwidth you can dedicate to periodic tasks because of the way they are implemented on the consumer side.

In contrast, Celery uses a special producer to put periodic tasks on the queue so they aren't tied to a specific consumer.

**Comment by coleifer** [comment]
Any consumer in the group will be able to run the periodic tasks. In this regard I believe huey is the same as celery. It's just a single consumer process that is in charge of enqueueing the periodic tasks, any consumer can execute them.

**Comment by tuukkamustonen** [comment]
> I experimented locally with multiple consumers and it appears that one consumer gets scheduled all jobs. This appears to due to the backoff param and the jobs being short lived.

I also ran similar experiment on top of the `count_beans` example in the docs (why beans?). I ran two consumers and when I started a batch of 100 jobs, one worker ran them all while the other one sat idle. Then I added 100ms sleep inside `count_beans()`, and re-run 100 jobs. This time, roughly 50% were run by first worker and another 50% by second. There was no duplication of parameters (I ran `for i in range(100): count_beans(i)`).

I would assume `BRPOP` that huey calls is safe for concurrent invocation (because Redis is single-threaded if not for anything else), but how about when there's a Redis cluster?

I think huey polling Redis once per second (insteading of getting async ) may confuse the user. In the first test, without delay, I guess one worker just happened to hit Redis first and ran all the jobs quickly before the second one could poll anything. When I added some latency, both consumers found work.

**Comment by coleifer** [comment]
When you instantiate Huey object, specify "blocking=True" and you will get BRPOPs.

http://huey.readthedocs.io/en/latest/api.html#Huey

**Comment by tuukkamustonen** [comment]
Oh, right. So by default huey does `RPOP`. It executes that in interval defined by `delay`/`backoff`/`max_delay`.

When you enable `blocking=True`, how long does huey worker keep the `BRPOP` open waiting for data? I see the default timeout is 1 (second), but is that timeout for reading the data when it becomes available? If it's timeout for wait time... will huey re-run brpop after timeout? I see nothing related to that in the logs.

> huey polling Redis once per second

Looks like this wasn't true either, I confused it with scheduler interval (1s by default). Scheduler runs future and periodic tasks and has no impact on running "ad-hoc" or instant tasks.

Still about scalability: I'm no redis expert so by a quick glance it seems Redis "simply" shards data when run in a cluster. I see no reason why huey would not work also in such environment, though I assume you would need to run separate workers per cluster instance, to keep polling/waiting for data in every shard.

**Comment by coleifer** [comment]
You can specify a timeout, called `read_timeout`, which is 1 by default. This is to avoid the client getting stuck in a bad state which some users reported. You can bump that up to 300, 600, 86400 whatever.

**Comment by tuukkamustonen** [comment]
Yeah but what is that timeout exactly: If it is read timeout for receiving data when there is something to return, is there another timeout for defining how long huey waits for BRPOP to return something? And what happens after that timeout, a new BRPOP call?

**Comment by coleifer** [comment]
It is the amount of time to wait for the BRPOP to return something. If it doesn't return something in X seconds, then it will fire off another BRPOP immediately.

**Comment by ranihorev** [comment]
Hey,

Following the questions above, is there an option to run multiple (2 in my case) consumers using Django.
I have 2 types of tasks and I don't want them to affect each other. For example, one of the types could wait and block the consumer, and I want all other tasks from the same type to wait in line, but to keep running tasks from the second type.

I hope it's possible using Huey.
Thanks!

**Comment by coleifer** [comment]
That should be possible, but I'm not sure how easy it will be considering you're using Django... The huey integration for Django creates a single `huey` object per project, so I'm not sure how you'd divvy up the tasks. If you were using Flask, it'd be quite easy:

```python
huey = Huey('my_app')
huey_long_tasks = Huey('my_app.long_tasks')

@huey.task()
def short_task():
    ...

@huey_long_tasks.task()
def long_task():
    ....
```

Then you could run two consumers, one pointing at each `huey` instance.

For Django, it's slightly more complicated because Huey only creates a single `huey` object.

**Comment by ranihorev** [comment]
Thanks for the quick reply. 
I guess I'll have to find a replacement (I love Huey!). 
I thought about django-rq. Do you have any recommendations?
