### ISSUE TITLE
Supporting backends other than Redis?

### ISSUE THREAD

**Issue by JordanReiter** [coleifer/huey#219]
Looking over your code and it seems very strongly coupled with Redis.

That's fine, but seeing as you did set up a BaseStorage class I'm wondering your thoughts on allowing alternate backends?

**Comment by coleifer** [comment]
I definitely set out to make it possible to use other backends. The Redis implementation is the default and works extremely well, of course, but there's also a SQLite implementation included in the source tree (undocumented at the moment, though):

https://github.com/coleifer/huey/blob/master/huey/contrib/sqlitedb.py

Was there a particular tool you were wanting to use instead of Redis?

**Comment by coleifer** [comment]
closing. don't create frivolous issues in the future on my projects you clown.

**Comment by JordanReiter** [comment]
I'm very sorry. I got inundated with work and haven't had any time for any spare time coding. I apologize for not responding. 

To answer your question, I was hoping it might be possible to support AWS services (possibly SQS?)
