### ISSUE TITLE
Crontab: day_of_week

### ISSUE THREAD

**Issue by BennyAlex** [coleifer/huey#241]
Hello,
I was wondering whats the right day_of_week configuration for huey.
`Is day_of_week='0'` sunday or monday? 
I saw this line  
```
# fix the weekday to be sunday=0
w = (w + 1) % 7
```
For me it looks like that the value will always + 1, why?

In a ubuntu cron explanation, I saw that 0 and 7 are both sunday, huey does not support 7, right?

**Comment by coleifer** [comment]
The `timetuple()` function returns the day of week such that Monday=0 and Sunday=6. We want to normalize this so that Monday is not 0, but 1.

So Python's timetuple() tells us:

* 0 = Mon
* 1 = Tues
* 2 = Weds
* 3 = Thurs
* 4 = Fri
* 5 = Sat
* 6 = Sun

Huey uses:

* 0 = Sun
* 1 = Mon
* 2 = Tues
* 3 = Weds
* 4 = Thurs
* 5 = Fri
* 6 = Sat

The `(w + 1) % 7` accomplishes the conversion from Python value to Huey value.

In terms of inputs, huey validates that the day-of-week is within the range of 0 - 6, so specifying 7 would cause a value error:

```python
In [8]: crontab(day_of_week=7)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-303db3d885b0> in <module>()
----> 1 crontab(day_of_week=7)

/home/charles/code/huey/huey/api.pyc in crontab(month, day, day_of_week, hour, minute)
    642                 piece = int(piece)
    643                 if piece not in acceptable:
--> 644                     raise ValueError('%d is not a valid input' % piece)
    645                 settings.add(piece)
    646 

ValueError: 7 is not a valid input
```

**Comment by coleifer** [comment]
I've updated the docs to clarify the valid inputs and their corresponding day.

**Comment by BennyAlex** [comment]
@coleifer 
But sunday 0 is still a bit weird, maybe allow that 7 is sunday too?

**Comment by coleifer** [comment]
Added. a1802fd91342975c788399f74a2792467a532043
