### ISSUE TITLE
Instances of a periodic task have the same id?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#264]
```
18:27:55 INFO Huey consumer started with 1 process, PID 7663
18:27:55 INFO Scheduler runs every 1 second(s).
18:27:55 INFO Periodic tasks are enabled.
18:27:55 INFO UTC is enabled.
18:27:55 INFO The following commands are available:
+ count_beans
18:28:55 INFO Scheduling periodic task queuecmd_count_beans: 8ac89f92-8480-4a92-8e4f-d2ce88c05a5a.
18:29:02 INFO Executing queuecmd_count_beans: 8ac89f92-8480-4a92-8e4f-d2ce88c05a5a
-- counted 100 beans --
18:29:55 INFO Scheduling periodic task queuecmd_count_beans: 8ac89f92-8480-4a92-8e4f-d2ce88c05a5a.
18:29:59 INFO Executing queuecmd_count_beans: 8ac89f92-8480-4a92-8e4f-d2ce88c05a5a
-- counted 100 beans --
```
Is it a bug that all instances of a periodic task have the same id?

**Comment by coleifer** [comment]
Yeah...let me look into it.

**Comment by coleifer** [comment]
51f951e4c942577489ee0b9f720860fe4c1dff53

**Comment by mindojo-victor** [comment]
Since periodic tasks have their own ids, does make sense to store their results too?
https://github.com/coleifer/huey/blob/07164083f6357d63a2a192961b74c61b4fb74ebd/huey/api.py#L379

**Comment by coleifer** [comment]
Semantically I never felt it made sense to store periodic task results. If they're doing an important computation, theoretically that would involve manipulating a relational database/reporting/etc.

If you weren't careful it could also mean clogging up your result store with a ton of results -- i.e. a task that runs every minute and, purely by accident returns an integer, would store 1,440 results a day.

**Comment by mindojo-victor** [comment]
I think we should not limit what a periodical task does.

A compromise would be to not store the result if it's None.

**Comment by coleifer** [comment]
So to fetch the result of a task you would, theoretically, want to have the actual `TaskResultWrapper` instance handy -- since this provides APIs for querying the data-store for the task result. Alternatively knowing the task's ID would work (via a call to `Huey.result()`). In either of those cases, though, to get at the task result you would need information from the `QueueTask` instance.

Periodic tasks are enqueued by the consumer, so the application really has no knowledge of the task ID or way to get at the `TaskResultWrapper` instance (if one existed for the periodic task).

So to my thinking, it doesn't make sense to store the results since there's no real way to get at them from the application.

If you're dead set on storing the result you can always use the result-store APIs directly in your periodic tasks.
