### ISSUE TITLE
Task failure callback

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#275]
I have a task

```python
@app.task(retries=3, retry_delay=60*5)
def send_email(...):
    ...
```

If this task fails after all retires I want to make an action, for example notify someone that the used did not receive the email.

What is the best way to do this? Celery does it through apply_async ( http://docs.celeryproject.org/en/latest/userguide/calling.html#linking-callbacks-errbacks ).

**Comment by coleifer** [comment]
You'll probably want to pass `retries_as_argument=True` in your task declaration, so that the `send_email()` function will receive the current number of retries as a parameter. Alternatively you could specify `include_task=True` and then the whole `task` instance would be passed as an argument to `send_email()` which could the inspect `task.retries`.

Ex:

```python
@app.task(retries=3, retry_delay=60*5, include_task=True)
def send_email(to, subj, body, task=None):
    try:
        _send_email(to, subj, body)
    except Exception as exc:
        if task.retries == 0:
            notify_of_task_failure(task)
        raise
```
