### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#313]
`huey.consumer.Consumer.worker_threads` right now is a list of tuples `(worker, process)`.

But the first item is never used, because it is recreated each time ( https://github.com/coleifer/huey/blob/0447c6046e7475ec31e9d0796ccc6c7f906bfaef/huey/consumer.py#L589 ). `worker_threads` can be a list of processes instead to make the code simpler to understand and maintain.

**Comment by mindojo-victor** [comment]
I found `worker` used in tests. I just don't understand how it could be useful, because AFAIR it's in the consumer process. Maybe it makes sense in threading implementation, but in multiprocessing environment -- I don't see how.

**Comment by coleifer** [comment]
Why is this an issue?

**Comment by coleifer** [comment]
I'm grateful for the issues you've raised as they've led to Huey becoming a better library for everyone.

By "code quality" you are referring to the fact that an internal consumer data-structure is ``list<(Worker, worker_t)>`` instead of ``list<worker_t>``.

I do not plan on changing this, as I think it's clean and symmetrical to keep the worker instance alongside the thread/process that's running it.

**Comment by coleifer** [comment]
You're correct. It makes things like testing easier to have the worker class and the associated process in the same data-structure, because once you wrap the worker class in a greenlet/thread/process, there's no way to reference it after the fact. It's not being used outside of the tests, at present, though. Perhaps I can make some better comments.

**Comment by mindojo-victor** [comment]
> Huey becoming a better library
As a library it's not always user friendly.

Are you still against allowing easily overriding internals?

For example I have to monkey-patch to name tasks not as `'queue_task_%s' % (func.__name__)`:

```python
# Monkey-patch the function, because we require our own template for task names
def create_task(task_class, func, retries_as_argument=False, task_name=None,
                include_task=False, _orig_create_task=huey.api.create_task, **kwargs):

    task_name = task_name or f'{func.__module__}.{func.__name__}'
    return _orig_create_task(
        task_class,
        func,
        retries_as_argument=retries_as_argument,
        task_name=task_name,
        include_task=include_task,
        **kwargs
    )


huey.api.create_task = create_task
```

I would be much nicer if `create_task` would be a method of `TaskWrapper`. And `TaskWrapper` to be used would be  a class attribute of `huey.api.Huey`:

```python
class Huey(object):
    task_wrapper = TaskWrapper

    ...

    def task(self, retries=0, retry_delay=0, retries_as_argument=False,
             include_task=False, name=None, **task_settings):
        def decorator(func):
            ...
            return self.task_wrapper(...)
        return decorator

```

I just don't understand why you don't want this approach. It doesn't make the code more complicated but gives more flexibility to others to override/extend the default behavior without monkey-patching and other ugly approaches.

The same approach can used to configure which `Worker`, `Consumer`, `Scheduler` classes to use.

**Comment by coleifer** [comment]
I feel like if Huey is a well-designed library then it will be easy to extend. It's not an explicitly-stated project goal to make all the internals override-able. A good rule of thumb is that the 80% case should be easy and the 20% case should be possible.

> Are you still against allowing easily overriding internals?

When did I say this? I think you might want to look at your attitude and see what's going on -- there's an *entitled* vibe coming across that you may not be aware of.

> For example I have to monkey-patch to name tasks not as 'queue_task_%s' % (func.__name__)

Really? I thought that the `task()` decorator's `name` parameter would allow you to accomplish this, e.g.:

```python
@huey.task(name='foo.bar')
def foo_bar(a, b):
    return a + b
```

**Comment by mindojo-victor** [comment]
I did override `task` decorator to set the name to what I want, but then it turned out I also have to override `periodic_task` -- and doing the same thing in two places is not fun. Both of the decorators are creating a `TaskWrapper`, so I thought it's a good place to put the common logic there. But I can't, as I explained above.

**Comment by mindojo-victor** [comment]
> When did I say this?

I suggested the same thing here https://github.com/coleifer/huey/issues/265#issuecomment-337261204

But you suggested to use an uglier way. So I made the conclusion that you don't want to make it easier to override the internals.

> there's an entitled vibe coming across that you may not be aware of.

Sorry, I am not a native English speaker, so I am not sure what this idiom means. But I think I understand what you mean.

I feel like I am fighting with you. To me it looks like you oppose some of changes. I kind of understand why, but I don't think it's wise.

That's were my attitude comes from. 

So I think I could address the same quote to you... :)

**Comment by coleifer** [comment]
Something to bear in mind is that many, many people use this library happily (myself included). The public APIs are all documented, as is the behavior of the consumer. The test suite covers the documented APIs as well as some of the trickier internal bits. These are, to me, indications that the project is healthy.

I don't know the details of what you're trying to implement, but it sounds like you are making significant modifications to the library and are deep into the internal data-structures.

Huey is a task-queue. It's *not* a task-queue framework. I hope you understand the difference.

As I said earlier, my goal is to make the 80% use-case easy and the 20% use-case possible. Having clean, orthogonal APIs throughout is a good way to ensure this is possible. But because you are having some very specific issue overriding some very specific internal behavior doesn't necessarily indicate there's a bug that needs to be fixed.

> I feel like I am fighting with you.

You're only going to wear yourself out if you feel that way.

**Comment by mindojo-victor** [comment]
> These are, to me, indications that the project is healthy.

I think the project is healthy and the code is nice.

> As I said earlier, my goal is to make the 80% use-case easy and the 20% use-case possible. Having clean, orthogonal APIs throughout is a good way to ensure this is possible. But because you are having some very specific issue overriding some very specific internal behavior doesn't necessarily indicate there's a bug that needs to be fixed.

Well, I pose this issue not as a bug. Just as an issue. Changing two lines in `consumer.py` would make my life easier and would not changer the original code more complicated.

I can submit a PR, to take less of your time, but I am not sure you will accept it, because it looks to me you oppose the very idea.

> You're only going to wear yourself out if you feel that way.

Well, that's my job: to make my apps better so I have to fight over some architecture decisions sometimes. I try to not take it personally.
