### ISSUE TITLE
Running workers with different tasks available

### ISSUE THREAD

**Issue by blakev** [coleifer/huey#314]
I'm running `huey` in a Docker environment and need the ability to run additional workers specific to certain tasks.

If my tasks are:

- download
- extract
- upload
- build

I only need 1 worker for download and upload, but need 2 extraction workers for every 1 build process. (`1 + N + 2*N`) This is easy enough to do using Docker and auto scaling, however it's increasingly difficult with the "all or nothing" approach to available tasks.

My suggestion is adding an optional parameter to `@task` called `group=None`, which could be filtered at run time via a `-g --task-groups` argument to only run the tasks defined in a comma separated list.

**Comment by coleifer** [comment]
The currently-supported approach for this is to use multiple `Huey()` instances for the distinct task groups.

The reason why "groups" wouldn't work has to do with the underlying storage system. A typical huey setup will have a single `Huey` instance, which is using a Redis server for storage. Tasks are added to a Redis LIST specific to the `huey` instance whenever they should be executed. The consumer, in turn, reads tasks from this Redis LIST and distributes them as workers become available. "Groups" won't work because you could find yourself in a scenario where a consumer receives a task on the queue, but the task is not in any groups it's configured with...so what does it do with the task? Re-enqueue it and hope that a different consumer picks it up eventually? It doesn't work.

Instead, you should use 2 (or more) `huey` instances and configure them as you see fit. When running the consumers you can provision them with workers as appropriate.

**Comment by kunaldawn** [comment]
> The currently-supported approach for this is to use multiple `Huey()` instances for the distinct task groups.
> 
> The reason why "groups" wouldn't work has to do with the underlying storage system. A typical huey setup will have a single `Huey` instance, which is using a Redis server for storage. Tasks are added to a Redis LIST specific to the `huey` instance whenever they should be executed. The consumer, in turn, reads tasks from this Redis LIST and distributes them as workers become available. "Groups" won't work because you could find yourself in a scenario where a consumer receives a task on the queue, but the task is not in any groups it's configured with...so what does it do with the task? Re-enqueue it and hope that a different consumer picks it up eventually? It doesn't work.
> 
> Instead, you should use 2 (or more) `huey` instances and configure them as you see fit. When running the consumers you can provision them with workers as appropriate.

exactly what i was looking for
