### ISSUE TITLE
enqueue the jobs which are in the error queue

### ISSUE THREAD

**Issue by huangxiaohen2738** [coleifer/huey#340]
If the jobs in error queue, how can I enqueue them again?

**Comment by ChefJ** [comment]
Hey dude.

using this may can help you checking the task status.(and maybe you can re-enqueue the task when failed)
https://huey.readthedocs.io/en/latest/events.html?highlight=huey.storage

however, I failed to use this 'storage' thing....

Good luck to you and I'll Really appreciate if you can share your progress.

**Comment by huangxiaohen2738** [comment]
Maybe it's a trouble. Because,  the task has not arguments which was in the error queue.
Loads the error info which in error queue, I get: 

`{'retries': 0, 'task': 'queue_task_test', 'traceback': 'Traceback (most recent call last):\n  File "xxxx/api.py", line 380, in execute\n    result = task.execute()\n  File "/xxx/huey/api.py", line 880, in execute\n    return func(*args, **kwargs)\n  File "/xxxx/task.py", line 78, in test\n    raise\nTypeError: exceptions must be old-style classes or derived from BaseException, not NoneType\n', 'execute_time': None, 'error': "TypeError('exceptions must be old-style classes or derived from BaseException, not NoneType',)", 'retry_delay': 0, 'id': 'e2a41d7c-9896-49ee-9c7d-c70f8720bd69'}`

I want to run again,  but no arguments

**Comment by coleifer** [comment]
The error store is not designed to be used for re-enqueueing tasks. If you want to retry tasks that have errors, specify `retries` in your task declaration.

There's an additional problem with including the task data in the error queue -- it can frequently result in problems pickling, which is why it's not `True` by default.

You can, if you want, subclass `RedisHuey` and override the signature of `_get_task_metadata` to always include the data for errors:

```python
class MyRedisHuey(RedisHuey):
    def _get_task_metadata(self, task, error=False, include_data=False):
        return super(MyRedisHuey, self)._get_task_metadata(task, error, include_data=error)
```
