### ISSUE TITLE
task.get(blocking=True) block forever if @task() does not return a value.

### ISSUE THREAD

**Issue by ChefJ** [coleifer/huey#349]
The Code below works as expected.
```
@task()
@lock_task('sleeplock')
def sleeptest():
    tasks = []

    for i in range(1,2):
        tasks.append(sleeptestworker())

    for task in tasks:
        print("start")
        task.get(blocking=True)

    print("All tasks are ready to fight.")
    
@task()
def sleeptestworker():
    print(str(datetime.datetime.now())+" I'm going bed.So sleepy!")
    time.sleep(10)
    print(str(datetime.datetime.now())+" I'm getting up.Energy max!")
    return 1
```

However, I don't really need the `return 1` part .But if without it ,the `task.get(blocking=True)` will be blocked forever and `sleeptest()` will never run to `print("All tasks are ready to fight.")`, nor will it release the `sleeplock`.

These codes below will not come through the 'block':

```
@task()
@lock_task('sleeplock')
def sleeptest():
    tasks = []

    for i in range(1,2):
        tasks.append(sleeptestworker())

    for task in tasks:
        print("start")
        task.get(blocking=True)

    print("All tasks are ready to fight.")
    
@task()
def sleeptestworker():
    print(str(datetime.datetime.now())+" I'm going bed.So sleepy!")
    time.sleep(10)
    print(str(datetime.datetime.now())+" I'm getting up.Energy max!")
    return     
    #returning nothing blocks the function
```

```
@task()
@lock_task('sleeplock')
def sleeptest():
    tasks = []

    for i in range(1,2):
        tasks.append(sleeptestworker())

    for task in tasks:
        print("start")
        task.get(blocking=True)

    print("All tasks are ready to fight.")
    
@task()
def sleeptestworker():
    print(str(datetime.datetime.now())+" I'm going bed.So sleepy!")
    time.sleep(10)
    print(str(datetime.datetime.now())+" I'm getting up.Energy max!")
    #no returning also blocks the function 
```

If this is not a issue..I recommend that 'all task should return a value' should be written in the doc..

**Comment by coleifer** [comment]
This is expected, since you're using the task result-storage APIs for synchronization (rather than for what it's intended use-case is, namely: the storage of task results). You're depending on huey to store a result for task that does not return a result, so you can determine that the task is finished.

By default, Huey does not store `None` results in the result-store. This is to avoid needlessly clogging up the storage system with tasks that do not return a meaningful result.

You can explicitly store `None` results, by: `huey = RedisHuey(..., store_none=True)`.

Documented here: https://huey.readthedocs.io/en/latest/api.html#Huey
