### ISSUE TITLE
Feature request: consumer with auto reload for developing...

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#359]
I thinks it's usefull to have a consumer command with auto-reload feature for developing.

It's not quite as easy as I tried in #358

**Comment by coleifer** [comment]
Not interested...auto-reloading tasks, particularly a consumer, seems misguided. Also it seems you're using this with Django. Typically when doing huey development with Django, huey is run in "always_eager" mode (due to settings.DEBUG being True) ... so your tasks autoreload when your django dev server restarts.

Presumably you'll only be running an actual huey consumer when actually running your django app outside of debug mode, and in that case your django code won't be reloading anyways.

**Comment by jedie** [comment]
Ah! I didn't realize that the task is executed in "always_eager" mode and you don't need a separate consumer process. That's great.

**Comment by schettino72** [comment]
What about development NOT using django? Manually reloading the consumer is not productive.

**Comment by coleifer** [comment]
Use `always_eager` (??)

**Comment by schettino72** [comment]
I am using the `huey_consumer` command line. Did not see an option `immediate`...

Actually solved my problem by using the PROCESS worker instead of default THREAD.
Since there is no process poll, new tasks pick-ups code changes.

**Comment by coleifer** [comment]
Instead of doing that, you could also read the documentation. I even linked it helpfully for you.

`immediate` mode is designed for use when developing, as it runs all your tasks in-process and doesn't require you to run the consumer while you're working.

**Comment by schettino72** [comment]
Thanks for the link. But really, not what I was looking for (I want reload tasks code without using application process). 
The PROCESS worker just do what I want... I guess a note on docs would be helpful for people searching for "reload" keyword.

Thanks for great project.

**Comment by coleifer** [comment]
The proper way is to send sighup to the consumer if all you want is restart.

**Comment by michal-michalak** [comment]
You can use watchdog for auto-restarting 😉 

```
watchmedo auto-restart --signal SIGHUP --directory . --recursive --pattern '*.py' -- python manage.py run_huey
```
