### ISSUE TITLE
on_complete does not behave as expected

### ISSUE THREAD

**Issue by chrisk314** [coleifer/huey#365]
I'm just starting out with Huey as an alternative to Celery for a Django app I'm working on. I'm liking Huey a lot so far, so thanks a lot for writing it. One use case for async tasks in my current project is to send an email after another task has completed. In this instance the function responsible for sending the email is completely agnostic towards the return value of the task on which it depends; it just needs to execute after the other task has finished. I tried using pipelines but it seems that there is no way to create a pipeline of tasks in which child tasks don't take the return value of their parent task as an argument. From reading the docs and looking at the code a bit it seems like I should be able to acheive what I'm after using the `on_complete` method of the `QueueTask` object; however, the results are not what I expect as illustrated by this simple example:

``` python
from huey.contrib.djhuey import HUEY, task


@task()
def add_2(x):
    return x + 2


t = add_2.s(2)

t.on_complete = add_2.s(8)

q = HUEY.enqueue(t)

print(q)
# Expected output: [4, 10], Actual output: [4, None]
```

In the above example I just want the `on_complete` task to run after the first and return the result in the results set produced by `enqueue`. Instead of the second task producing the expected result of `10`, `None` is produced. Perhaps I'm completely misunderstanding or missing the point of the `on_complete` method and this is the expected behaviour, apologies if that is the case. There is almost no detail that I could see about how `on_complete` should be used in the docs. Is there a way to acheive what I'm trying to do with Huey?

**Comment by coleifer** [comment]
Couple thoughts...

You shouldn't assign `.on_complete` - that's why it's not documented, really. The docs show you how to create a pipeline -- the assumption is that if your task returns a value *and* you are using a pipeline, you want to carry the return value forwards -- (otherwise just call the tasks serially). [Documentation for pipelines](https://huey.readthedocs.io/en/latest/getting-started.html#task-pipelines).

In your example, it may be returning `None` because the queue hasn't processed the second item yet, so be sure you call `.get(blocking=True)` when resolving the results of a pipeline, e.g.

```python
@huey.task()
def add2(x):
    return x + 2

t = add2.s(4).then(add2)  # No args, it will receive the return value.
res1, res2 = huey.enqueue(t)
print(res1.get(blocking=True))  # 6 (2 + 4)
print(res2.get(blocking=True))  # 8 ( 2 + 6, previous return value)
```

If your task does not return a value, then of course nothing is carried forward:

```python
@huey.task()
def dont_carry_results(msg):
    print(msg)

t = dont_carry_results('message1').then(dont_carry_results, 'message2')
huey.enqueue(t)

# Consume will print "message1", then "message2".
```

So I believe I've shown how to use pipelines correctly with argument passing, answered the question about `None` in the results, and also shown how to construct pipelines that do not pass a return value.

You said you don't care about the return value of the first task, they just need to happen in order. You can write a third task that calls both functions in succession?

```python
@huey.task()
def generate_report()
    actually_generate_the_report()

@huey.task()
def send_email(message):
    actually_send_the_email(...)

@huey.task()
def generate_report_and_send_email():
    report = actually_generate_the_report()
    actually_send_the_email(report)
```

In the above code, calling `generate_report_and_send_email()` is pretty much equivalent to:

```python
t = generate_report.s().then(send_email)
report, email_result = huey.execute(t)
```
