### ISSUE TITLE
Store results of periodic tasks

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#394]
Do I understand correctly that this code ignores result of periodic tasks because they didn't have own task ids originally?

https://github.com/coleifer/huey/blob/7b4fc3eea819d5417f510b7ec2bf116b26fafbe9/huey/api.py#L417-L419

If yes, looks like it's obsolete:

> periodic task instances now have their own
unique task ID.

https://github.com/coleifer/huey/commit/5f1318663722deca079a5ae5552679e81e4d8d09

**Comment by coleifer** [comment]
It's still the case that the return values of periodic tasks are not stored:

```python
        if self.result_store and not isinstance(task, PeriodicQueueTask):
            if result is not None or self.store_none:
                self.put(task.task_id, result)
```

They *do* have their own unique ID, but they are not stored.

**Comment by coleifer** [comment]
The reason for this is described in the commit I just pushed, 1c39de8

> The result (return value) of a periodic task is not stored in the
result store. This is primarily due to the fact that there is not
an obvious way one would read such results, since the invocation of
the periodic task happens inside the consumer scheduler. As such,
there is no task result handle which the user could use to read the
result. To store the results of periodic tasks, you will need to
use your own storage.

You can of course manually put results in the result store:

```python
@huey.periodic_task(...)
def my_periodic_task():
    # do some stuff
    huey.put('my-periodic-task', some_result_obj)
```

**Comment by mindojo-victor** [comment]
Are planning to make a release?

**Comment by coleifer** [comment]
Releasing one now.
