### ISSUE TITLE
Prioritizing the execution of certain tasks

### ISSUE THREAD

**Issue by bptarpley** [coleifer/huey#401]
I have greatly enjoyed using Huey over Celery in my Django project. Fantastic tool! One question I have, however, is whether I could a) have a task that, when fired, immediately takes priority of anything else in the queue, and b) have a periodic task that always runs when scheduled, regardless of whatever else is in the queue.

Basically, I intend to have moments where hundreds of tasks are enqueued, but I need to still be able to prioritize a subset of tasks so that a full queue won't prevent them from running.

Many thanks in advance!

**Comment by vrbrito** [comment]
@bptarpley 

On Issue #294, it's suggested to use multiple queues with that purpose. I myself did that to solve my problems, but I used an extension called [hueyx](https://github.com/Sebubu/hueyx) that adds support to multiple queues in Django environment.

**Comment by coleifer** [comment]
Task priorities are implemented in the 2.0a branch, which will become the 2.0 release of Huey fairly soon.

2.0a code: https://github.com/coleifer/huey/tree/2.0a

2.0a docs: https://huey.readthedocs.io/en/2.0a/

Priority docs: https://huey.readthedocs.io/en/2.0a/guide.html#task-priority

**Comment by bptarpley** [comment]
This is wonderful news! Many thanks, @coleifer, for taking the time (and so quickly) to implement priority functionality. I'm excited to take it out for a spin 👍 

Also, @vrbrito, I appreciate you taking the time to share info about hueyx--I can imagine scenarios where someone might want a queue fulling dedicated to running certain tasks. For my purposes, though, I prefer the simplicity of using a single package and a single queue.

**Comment by coleifer** [comment]
Well, I'd been working on mostly rewriting huey as of a couple weeks ago, and thanks to the changes I was able to implement priority support quite easily (as you can see from the [relevant diff](https://github.com/coleifer/huey/compare/401740f...72d2b5c7)).

Priority support was trivial to add to the sqlite storage layer. For redis, I decided that I could use some nice features available in 5.0 by moving the queue itself from a plain old list to a sorted-set. (b)zpopmin allows huey to very simply pop items from a sorted set based on min score. All-in-all quite simple. Rather than forcing users to use redis 5.0, though, the redis priority stuff is implemented in a separate storage layer, via `PriorityRedisHuey` (as opposed to `RedisHuey`, which has not changed).

**Comment by bptarpley** [comment]
Awesome. I saw in the docs how Redis 5 will be required for PriorityRedisHuey--it's good to know why that's the case. Thanks again.
