### ISSUE TITLE
Question: Async tasks...

### ISSUE THREAD

**Issue by edelvalle** [coleifer/huey#441]
First of all, thank you very much for huey...

what is I have an async tasks? like...

```python
@huey.task()
async def async_stuff_todo():
    await some_async_magic()
```

I made this decorator

```python
def wait_for(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        return asyncio.run(f(*args, **kwargs))
    return wrapper
```

So I decorate the task like

```python
@huey.task()
@wait_for
async def async_stuff_todo():
    await some_async_magic()
```

And it works when using, the HueyRedis you can call it as

```python
tasks.async_stuff_todo()
```

Without `async`, but when testing and running in immediate mode I get this error:

```
.../lib/python3.7/sre_parse.py:477: RuntimeWarning: coroutine 'async_stuff_todo' was never awaited
  subpattern = SubPattern(state)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Any idea on how to have tasks that need to deal with async stuff?

**Comment by coleifer** [comment]
Huey doesn't support asyncio. It is not aware of the asyncio event loop. If you want, you can always use the gevent worker type.

**Comment by edelvalle** [comment]
thanks!

**Comment by dlindenkreuz** [comment]
> I wrote a decorator which can execute async tasks with a process worker.

For some reason, tasks were just not executed at all in my setup.

The following decorator worked for me. It uses [asgiref's `AsyncToSync`](https://github.com/django/asgiref/blob/main/asgiref/sync.py).

```python
from asgiref.sync import AsyncToSync

def synchronize[**P, R](coroutine: Callable[P, Coroutine[Any, Any, R]]):
    sync_call = AsyncToSync(coroutine)

    @functools.wraps(coroutine)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
        return sync_call(*args, **kwargs)

    return wrapper

@huey.task()
@synchronize()
def work():
    ...
```

**Comment by coleifer** [comment]
Tangentially related, but my earlier comment about asyncio now deserves an asterisk, because Huey now provides asyncio-friendly helpers for waiting for task results to arrive: https://huey.readthedocs.io/en/latest/contrib.html#asyncio

**Comment by cesarrodrig** [comment]
Building on @ShipraShalini example, I got huey to work with `greenlet` workers and `asyncio` tasks so it now runs them concurrently:

```python
import gevent.monkey

gevent.monkey.patch_all()

import asyncio
import functools


def run_async_task(async_func):
    @functools.wraps(async_func)
    def wrapper(*args, **kwargs):
        loop = get_running_loop()
        coroutine = async_func(*args, **kwargs)
        future = asyncio.run_coroutine_threadsafe(coroutine, loop)
        return future.result()

    return wrapper


def get_running_loop():
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        print("A new event loop was spawned.")
        asyncio.set_event_loop(loop)
        loop.run_forever()
    return loop


@huey.task()
@run_async_task
async def async_io_task(n):
    await slow_async_function(1)
    await slow_async_function(2)


async def slow_async_function(n):
    await asyncio.sleep(2)
    print("Finished", n)
```

Keep in mind that race conditions can still happen, so you have to make sure tasks are not operating on the same objects/data.

**Comment by evantahler** [comment]
@coleifer any plans to add async task support to huey?  That's the main thing missing for us to migrate away from celery...

**Comment by coleifer** [comment]
Using `async def` with huey tasks seems really dubious to me. Neither is it something supported. If you want it, then this issue contains comments from several people offering workarounds.

**Comment by evantahler** [comment]
Adding a little color to why `async` was interesting to us, and how I'm thinking about getting around this:

* Our application is built of many async services.  These services are generally agnostic "business services" that take some well-typed pydantic input and produce some output.  Think `CreateUser()` and `SendEmail()`.  They are all async because they likely interact with a database, API, etc.  These services are meant to be reusable by both our API (fastAPI), jobs (Celery --> Huey), tests, CLI, etc.
* So, to get all these async tasks running in Huey, we can just do something like this, which isn't a big deal:

```python
@huey.task
def background_job(**kwargs):
  return asyncio.run(some_async_service(**kwargs))
```

* One of the great things about Huey is that you can use the huey-decorated method anywhere-ish, and just wait for a response.  So if you have a controller that wants to wait for some background job to finish, it's really easy to enqueue a Huey task and sleep/wait until it is done

```python
# In some controller method
# start the job
response = background_job()
# wait for the job
while response is not None and response() is None:
  await asyncio.sleep(1)
# yay, the huey job is done; deal with response()
```

* But, now when you want to test that controller in an already async context, like perhaps a test-suite using `HTTPX`'s `AsyncClient`, things go a little haywire because `asyncio.run` will fail as we are already _within_ an async loop.  Huey already has great support for simplifying testing with `immediate` mode, and I want to use it!

```python
if "PYTEST_VERSION" in os.environ:
    print("Running tests, setting huey to immediate mode")
    huey.immediate = True
```

Where I'm landing is making a new decorator that we add to our huey jobs based on the `nest_asyncio` hack to re-use the same async loop you might already be in:

```python
import asyncio
import nest_asyncio
import functools


def ensure_async_awaitable(func):
    """
    Decorator to ensure that the function it wraps is a non-async function that can then use asyncio.run(), e.g. Huey tasks.
    Huey tasks will be called in one of 2 contexts: either they are the top-level function(ish) in the process, and there is no loop yet, or we are running tests in an an async context already and we need to re-use the current loop.
    """

    @functools.wraps(func)
    def wrapper_decorator(*args, **kwargs):
        try:
            loop = asyncio.get_event_loop()
            nest_asyncio.apply(loop)
        except RuntimeError:
            ...  # We are not in an async context, so we can use asyncio.run
        return func(*args, **kwargs)

    return wrapper_decorator
```

This ^ solves the testing and top-level normal huey husage:

```python
@huey.task
@ensure_async_awaitable
def background_job(**kwargs):
  return asyncio.run(some_async_service(**kwargs))
```
