### ISSUE TITLE
Getting task result from redis data store

### ISSUE THREAD

**Issue by kc1** [coleifer/huey#442]
[![enter image description here][1]][1]

I'm working with the huey task queue https://github.com/coleifer/huey in flask . I'm trying to run a task and get a task id number back from my initial function:

    @main.route('/renew',methods=['GET', 'POST'])
    def renew():
        print(request.form)
        user =request.form.get('user')
        pw =request.form.get('pw')
        res =renewer(user,pw)
        res(blocking=True)  # Block for up to 5 seconds
        print(res)
        return res.id

After running this I plug the outputted id (which is the same as the result in the screenshot) 

[![enter image description here][2]][2]

into :

    @main.route('/get_result_by_id',methods=['GET', 'POST'])
    def get_result_by_id():
        print(request.form)
        id =request.form.get('id')
        from ..tasking.tasks import my_huey
        res = my_huey.result(id)
        if res==None:
            res = 'no value'
        return res

However I'm getting 'no value'

How can I access the value in the data store?

Its also here : https://stackoverflow.com/questions/57413072/getting-task-result-with-python-huey-from-redis-data-store

  [1]: https://i.stack.imgur.com/67rUO.png
  [2]: https://i.stack.imgur.com/qzt9Z.png

**Comment by coleifer** [comment]
Result-store reads are destructive. So when you resolve the result in your view function, huey destructively reads the result. This is done so that the results of tasks do not fill up the result-store over time.

Instead I suggest using `res.get(blocking=True, preserve=True)`, which doesn't destroy the value after reading. Then, when you call `my_huey.result(id)` later, the result will be destroyed after reading.

But hear this...the result store is not supposed to be your database. If you need to store data, store it in a database. The result store is used for communication between the consumer and the caller, but is not your database.
