### ISSUE TITLE
Immediate execution in unit tests with Django

### ISSUE THREAD

**Issue by Crunchie** [coleifer/huey#482]
I am resurrecting and old Django project that uses Huey and Im trying to upgrade the Huey library from version 1.2.0 to version 2.1.3.

Our usage is very simple, we just have a few functions which get decorated like `@db_periodic_task(crontab(minute='*/1'))` . We then run Huey through the `manage.py run_huey` command.

After the upgrade I had to add `immediate=False` to my settings to be able to run with `DEBUG=True`. with immediate set to false our program works as expected and the tasks are correctly scheduled.

I am running into a problem with unit tests though. We have some tests that call the methods that are the huey tasks (the decorated methods) This didn't seem to be a problem in the old version, but now it seems it will only work if I set `immediate=True` in my settings for the tests.

Is there any way to avoid having separate settings for running the tests?

So far I have tried decorating my test methods with `@override_settings(HUEY = {'immediate': True,})` but this doesnt work. Stepping through in the debugger it seems the logic to read the settings in the huey code gets called well before the unit test, and the settings being overridden.

I have also tried changing my test to call `method_to_test.call_local()` this appears to correctly call the method, but my test then fails when I go and check the database (to verify the method did the right thing) with the following error
```
django.db.utils.InterfaceError: connection already closed
```

Is there any other approaches I should be taking?
Thanks

**Comment by coleifer** [comment]
Huey uses "immediate"-mode as a replacement for the pre-2.0 `always_eager`. Upgrade notes are here:

https://huey.readthedocs.io/en/latest/changes.html#summary

Immediate-mode is enabled by default if you are running with DEBUG on, as you noticed. You should never have DEBUG enabled on production, presumably, but you can always specify the setting explicitly in your settings files.

In short, I'm not sure how to help you because it seems that are a lot of assumptions and things baked-in to how you've written your app, your workflows, and your tests.

The answer is really simple, hopefully - immediate runs stuff immediately and in-process.
