### ISSUE TITLE
Storing results of periodic tasks

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#489]
https://github.com/coleifer/huey/blob/f30d14751fa259705bf65d8d67d4cb32365917bc/huey/api.py#L380

If periodic task instances now have their own unique ids, why don't we store the results?

I found this in the [docs](https://huey.readthedocs.io/en/latest/guide.html):

> Similarly, the return-value for periodic tasks is discarded, rather than being put into the result store. This is because there is not an obvious way for an application to obtain a Result handle to access the result of a given periodic task execution.

What do I do if I need a way to get results of periodic tasks? 

I think there shouldn't be a limitation in the code for storing the results. Those who don't need them just need to return None as periodic task result.

**Comment by coleifer** [comment]
The problem has never been storing them, the problem is how to your obtain the reference to them to read the result in the first place. Periodic tasks run without user intervention, so there's no result handle... As the docs state.

When results are not read, they sit in the result store taking up space. If you forget about this and start returning stuff in periodic tasks, you'll fill up your storage with junk. This limitation does not occur in practice because, as I said earlier, how would you even get the result in the first place? *Where* would you get it? When would you get it?

>What do I do if I need a way to get results of periodic tasks?

You can always use the result-store APIs directly, or store your data in a database or whatever.

**Comment by coleifer** [comment]
Also you asked the same thing last year. https://github.com/coleifer/huey/issues/394

It's a bit tiresome.

**Comment by mindojo-victor** [comment]
> Also you asked the same thing last year. #394
> It's a bit tiresome.

Sorry for that.

My use case is a bit different. The tasks and results are not immediately deleted from the DB, they automatically expire after 30 days and then deleted. I have an interface to see list of tasks and their statuses, I can also see the task result. This interface greatly simplifies debugging. 

I guess I now understand the motivation. Thanks for the feedback.

**Comment by coleifer** [comment]
Huey is not going to be a replacement for a database. Yeah, you can use it to store arbitrary blobs of key/value data, but you might consider using a db.
