### ISSUE TITLE
FIFO task queue?

### ISSUE THREAD

**Issue by miluChen** [coleifer/huey#497]
Hi, the first impression of a `task queue` for me is that tasks get in the queue and get picked up one by one FIFO. But I noticed `huey` does not pick up the task based on timestamp from `SqliteStorage`. Do we have to use `task.priority` to enforce the FIFO property? or am I missing something obvious here 😨

**Comment by coleifer** [comment]
Sqlite rowids may be reused when rows are deleted, so it's definitely possible that this is happening.  If you require strict FIFO behavior, I've added a new option `strict_fifo` which utilizes Sqlite's [autoincrement](https://www.sqlite.org/autoinc.html) functionality to ensure rowids are not reused. This is disabled by default, and changing the setting to True requires that you delete your database (or at the very least the task table), since sqlite cannot alter columns in existing tables.

**Comment by miluChen** [comment]
Thanks! Looking forward to the next release.

**Comment by miluChen** [comment]
After giving it another thought and considering it's a "**task queue**", I was wondering whether the default should be enabling the strict_fifo. 🤔
