### ISSUE TITLE
Configurable signal handler

### ISSUE THREAD

**Issue by karls** [coleifer/huey#514]
Hi @coleifer. Thanks for Huey.

We're evaluating Huey as a replacement for RQ and there is a lot to like here!

One hiccup is around how consumer signals are handled/interpreted. Since we're on Heroku, and Heroku [sends a SIGTERM](https://devcenter.heroku.com/articles/dynos#shutdown) right off the bat for a "graceful shutdown", means that the Huey consumer could be basically killed mid-action and thus lose work.

I don't think there is a way to configure what signals the Heroku dyno system sends — it looks like SIGTERM, followed by SIGKILL if the process hasn't shut down after 30 seconds — so we're wondering if there is scope in Huey to make signal handlers configurable?

I saw another issue outlining the same situation (#239) and there is a workaround in there, but the workaround feels like a hack.

Just wondering what your thoughts are on this. Cheers.

**Comment by coleifer** [comment]
I'd suggest wrapping the consumer, then, in a small bash script which traps/handles the signals as you would like it to.

Huey uses sigterm to stop everything because it's a task queue and who knows how long a misbehaving task might stay running for? If TERM was for "graceful" shutdown, you'd need to use SIGKILL to force stop which means no cleanup on any number of worker/child processes. Just as a side note, if you need exactly once/at-least once you might want something more robust than redis / huey anyways.

**Comment by karls** [comment]
Thanks for the answer.

> If TERM was for "graceful" shutdown, you'd need to use SIGKILL to force stop which means no cleanup on any number of worker/child processes.

Yeah.. I don't really understand why Heroku have done like that, probably because they want to have some guarantees that when they terminate a service, it really terminates, whether gracefully via TERM or "for sure" via KILL.

Wrapping is a good idea. Playing around with that now.

Another thing I realised is that if I have a task that's set to be retried N times and if the consumer is shut down or killed before the task has managed to successfully, the task won't be retried when the consumer comes back up, even if it had retries left. Not sure if that's intended or not.

> if you need exactly once/at-least once you might want something more robust than redis / huey anyways

Yep, makes sense.
