### ISSUE TITLE
callback function for task

### ISSUE THREAD

**Issue by minyoung90** [coleifer/huey#519]
Hello, I have tested Huey on Windows with Django, it works fine but after test, I am curious about Huey's design.

1.  callback function for task

```
from huey.contrib.djhuey import task, post_execute


@task(name='mul')
def mul(a, b):
    return a*b


@task(name='add')
def add(a, b):
    return a+b


@post_execute(name='mul')
def post_execute_hook_for_mul(huey_task, result, exception):
    if exception is not None:
        raise exception

    if huey_task.name == 'mul':
        print(f'Result of mul: {result}')


@post_execute(name='add')
def post_execute_hook_for_add(huey_task, result, exception):
    if exception is not None:
        raise exception

    if huey_task.name == 'add':
        print(f'Result of add: {result}')
```
above is mine what I tested. task() works well, but I don't know why the task has no callback function. after reading docs, I added 'post_execute' like above, but I think it is not efficient. is there a way to add a callback function to a task-related?

2. running consumer on windows
Sorry, this is just a question.
I want to use Huey on windows server, so how I can run consumer with Django? I mean, whenever I restart the server, should I type a command 'run_huey'?

thanks for the great works!

**Comment by coleifer** [comment]
There are many, many ways to write a handler that processes completed tasks. Since it's just Python you can wrap your tasks with another decorator of your own that does any additional processing, or compose functions to make a custom `task()` decorator. You can use the `post_execute()` hooks, too.

It's unclear what you're trying to do, so it's hard to offer concrete advice.

Regarding running the consumer on Windows, I have no advice or suggestions. Try stackoverflow.
