### ISSUE TITLE
RedisExpireStorage.peek_data and testing for existence of task result

### ISSUE THREAD

**Issue by cdosborn** [coleifer/huey#531]
`RedisStorage.peek_data` returns `EmptyData` when the task result does not exist. However, `RedisExpireStorage.peek_data` will return `EmptyData` only if the the result is not `None`. 

Not sure if this is something you would like to change, just seems inconsistent. In the first case, I can use `store_none=True`, and have a reliable way to check if a task result exists or not. I'm aware of the caveat's with `store_none`, which is why i'd prefer to use `RedisExpireStorage`. In any case, I can also use `has_data_for_key`. 

Thanks for the great library.

**Comment by coleifer** [comment]
Huey does not store `None` results by default, so this would only occur if you had explicitly asked huey to store the return of value of tasks that return None. Storing `None` is problematic because it will fill up the storage if you have a large volume of tasks and do not explicitly resolve their result values.

That said, one of the benefits of using the expires storage engine is to make storing None values somewhat less fraught. I've modified the implementation to more closely match the regular Redis storage.
