### ISSUE TITLE
Ability to specify TTL on locks

### ISSUE THREAD

**Issue by warmwaffles** [coleifer/huey#538]
It would be nice to be able to specify the TTL on a lock. Once the lock has been set and if the process terminates mid run, it leaves that lock in place.

Something like `huey.lock_task("foo-bar", ttl: 3600)` would be nice. Or some way to re-up the lock as the long task is running as well.

**Comment by coleifer** [comment]
This happens if you hard-shutdown the consumer while it's executing a locked task. If you find yourself doing this, you should restart the consumer with the "flush-locks" option. The task lock uses the storage api, which has no concept of ttl.

Alternatively, if you use redis, you can very easily write your own lock implementation.

**Comment by zeraien** [comment]
> You're welcome to execute that at startup using a startup hook or any other mechanism.

I am now, but i was bitten quite sharply in the butt by this a while back and some clearer documentation would have been epic I guess. Otherwise, huey has been a godsend to those of us too busy to learn the crazy world of celery and rabbitmq hehe.
