### ISSUE TITLE
Periodic Huey Task stuck stopped executing anything and large task go in Enque and 

### ISSUE THREAD

**Issue by AbhishekTDev** [coleifer/huey#547]
I have implemented a periodic function that triggers in 1 minute. In some scenario, this periodic task may take 20 minutes as well . I have implemented this Huey setup on 8 core machine. I observed  It ran well till it opens 8 periodic functions. After it, It enqueuing only and stuck. No task including the current running never went into the executed state. 

 periodic task may take 10sec to 20 -30 minutes on execution. Well in ideal scenario Huey should enque the periodic task but It should at least finish them one by one.

**Comment by coleifer** [comment]
I'm not sure what your issue is or what you are asking. If you have 8 workers and all 8 of them are stuck executing a task, then tasks will just be enqueued until a worker is freed up. It sounds to me like your tasks are not finishing. If you want to limit the concurrency to "1" then you can put a lock around the task. This is documented: https://huey.readthedocs.io/en/latest/guide.html#locking-tasks
