### ISSUE TITLE
periodic task in cluster environment

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#558]
I have a question to e.g.: 
```
@huey.periodic_task(crontab(hour='*/1'))
@huey.lock_task('reports-lock')
def generate_report():
    run_report()
```
If we have this in a cluster, it's not guaranteed that this task will be executed only once in 1 hour, isn't it?

e.g.: Huey consumer instance 1 starts the task. While the task is running a second instance can't start it again, because of `@huey.lock_task()` isn't it?
But if instance 1 task is finished, then the instance 2 can start it again.

There should be something like this: Start the processing in endless loops but always wait one hour after each execution.

So several instances can try to run the task, but only one will run at a time every hour.

Is something like this already possible?

**Comment by coleifer** [comment]
The lock-task will ensure that two instances of the task are never run, that part is correct (note that your crontab will run every minute, though, since minute defaults to '*' and '*/1' hour means every hour).

So if your crontab was (minute='0', hour='*'), it will only be enqueued once every hour. Something like this:

1. it's 12:00, the schedulers on instances 1 and 2 see that the generate_reports needs to run, so each enqueues a task to run this.
2. instance 1's consumer picks up the task and locks it and starts executing
3. instance 2's consumer picks up the task, sees that its locked, and fails
4. instance 1 finishes executing
5. -- nothing else will be run until 1:00, which will repeat (more or less) steps 1-4

If you want to continuously run the report, I'd suggest something like:

```python
@huey.task()
@huey.lock_task('report-lock')
def generate_report_task():
    run_report()
    # Enqueue the task to run again in 60s.
    generate_report_task.schedule(delay=60)

@huey.periodic_task(crontab(minute='0'))
def ensure_reports_running():
    generate_report_task()
```

This setup has a periodic task that runs once per hour and which kicks off the generate report task. The generate report task runs the reports, then schedules itself to run again in 60s, ensuring it is (more or less) always running.

**Comment by jedie** [comment]
Thanks for the feedback.

I don't understand why your suggestion should be better. For me it just looks more complex without any real advantage.

**Comment by coleifer** [comment]
I guess I didn't understand exactly what you were hoping to achieve, in that case.

**Comment by jedie** [comment]
Sorry for the confusion. The most important point was clarified: `lock_task()` works in cluster environment with more than one machine. Because the redis backend has the same information for all machines/processes, isn't it?

btw. In my case it would not be very critical if a task would be executed twice. But it would be stupid ;)
