### ISSUE TITLE
suggested livenessProbe to use for kubernetes pod running huey consumer?

### ISSUE THREAD

**Issue by rexroof** [coleifer/huey#562]
we have several huey_consumer processes running in containers in kubernetes.     I'm looking for a way to perform health checks on those huey_consumer processes.    I have been doing really "dumb" health checks by verifying the python process was running, but that isn't always useful. 

does anyone have a pattern they have used?  ideally we'd verify our tasks workers have actually completed some tasks in the last X minutes, or something similar. 

Sorry if this is the wrong place for this discussion.

**Comment by coleifer** [comment]
Why not set up a periodic task that puts something in an external storage that you can check? Just have it run every minute or every 10 minutes or whatever and update a counter or something or set a redis key w/a TTL (so that if it stops re-setting the key, the key won't exist).

Checking for the process itself is fine. Or if you're using the worker process model you can check for a certain number of processes.

**Comment by rexroof** [comment]
if I have 6 huey_consumer pods all working on the same task queue, how do I know which pods are actively completing tasks?

**Comment by rexroof** [comment]
Is there a place to talk with other huey users?    Doubt anyone will be browsing closed github issues.

**Comment by coleifer** [comment]
Presumably you can look at something in the environment (`os.environ`) and use a redis key or whatever that includes identifying information.
