### ISSUE TITLE
Possible to avoid a separate consumer process?

### ISSUE THREAD

**Issue by yogmk** [coleifer/huey#572]
[*This is more of a question than an issue*]

I'm using `bottle` for my python application and I want to queue incoming requests of certain endpoints in a queue to be executed off the request-response cycle.
As I understand, one needs to launch a separate process (`huey_consumer.py`) to pick up & run the tasks from the queue. My question is, is it possible to avoid launching separate program in addition to bottle app? The reason for asking is purely due to admin/deploy considerations, because my app setup already has many moving parts than I would like, all of which need their own configuration (and this setup is to be replicated on multiple hosts within our environment).

Can the consumer process be somehow integrated into a `bottle.py` application and be run as part of the web app?

**Comment by coleifer** [comment]
>My question is, is it possible to avoid launching separate program in addition to bottle app?

Yes, if you want to look into `MiniHuey`, which uses gevent and runs in-process. Since it uses greenlet it means that you shouldn't have CPU-bound tasks, but there are ways to work around them if that's the case. https://huey.readthedocs.io/en/latest/contrib.html#mini-huey

Otherwise you're probably going to have a bit of a hard time, but it's not impossible. In some of the unit tests I start up a full consumer and everything. The `huey` instance has a `create_consumer()` method which you can call to get a consumer instance, which in turn has methods for starting the various workers and the scheduler. I'd look there if you want something more robust than "mini-huey".

**Comment by coleifer** [comment]
Oh - you probably will want to attach a signal handler if you go with creating a full consumer inside your app process, so that you can handle shutting it down.
