### ISSUE TITLE
Scheduler and Consumer UTC Compatibility

### ISSUE THREAD

**Issue by VijayStroup** [coleifer/huey#578]
redis==3.5.3
huey==2.3.0

When I launch the consumer:
```bash
$ huey_consumer.py tasks.huey_tasks.huey
[2021-01-22 15:48:15,182] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 10414 at 2021-01-22 20:48:15.182085
[2021-01-22 15:48:15,182] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2021-01-22 15:48:15,182] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2021-01-22 15:48:15,182] INFO:huey.consumer:MainThread:The following commands are available:
+ tasks.huey_tasks.set_completed
+ tasks.huey_tasks.set_expired
```
The times listed here is my local time (EST).

My goal is to use UTC time. With the consumer being like above, I have to write my code as such:
```python
set_expired.schedule((
        _id.inserted_id,
        'started',
        dt_exp,
        book.To
    ), eta=datetime.now() + timedelta(minutes=5))
```

```python
huey = RedisHuey()

@huey.task()
def set_expired(_id, status, expires, to_number):
    """set booking to expired if it has reached its expiration"""

    db = mongo['businesses']['entities'].find_one({'number': to_number})['db']

    if status == 'started' and expires < datetime.utcnow() + timedelta(seconds=5):
        mongo[db]['bookings'].update_one({'_id': _id}, {'$set': {
            'status': 'expired',
            'expired_at': datetime.utcnow()
        }})
```

From this I have to tell the scheduler to schedule the task for an eta that is using my local time rather than utc time. From what I've read, the consumer is supposed to use utc as default, so I'm not sure why it's using my local time.
In essence, I would like to be able to change my code to this:
```python
set_expired.schedule((
        _id.inserted_id,
        'started',
        dt_exp,
        book.To
    ), eta=datetime.utcnow() + timedelta(minutes=5))
```

Edit: Disregard the following part, I was looking at an older version it seems.
Also according to your [documentation](https://huey.readthedocs.io/en/latest/consumer.html), this should exist:
```python
$ huey_consumer.py tasks.huey_tasks.huey -u
Usage: huey_consumer.py [options] path.to.huey_instance

huey_consumer.py: error: no such option: -u
```

**Comment by coleifer** [comment]
Huey by default assumes you want to run in UTC and therefore converts naive localtimes to UTC internally. You can disable this with `RedisHuey(..., utc=False)`.

Docs: https://huey.readthedocs.io/en/latest/api.html#Huey

The problem is that disabling this essentially makes Huey use localtime everywhere.

Probably a better option is to leave the `utc=...` parameter alone and specify a tz-aware UTC timestamp for your schedule ETA.

**Comment by VijayStroup** [comment]
I think you may have misinterpreted my question:
I am not trying to use local time at all for scheduling tasks, I am trying to use UTC which should be default.

Here again is the call to set a new task:
```python
    t = datetime.utcnow() + timedelta(seconds=5)

    print(f'Current time UTC: {str(datetime.utcnow())}')
    print(f'Current time local: {str(datetime.now())}')
    print(f'Scheduled eta: {str(t)}')
    set_expired.schedule((
        _id.inserted_id,
        'started',
        dt_exp,
        book.To
    ), eta=t)

# output
# 
```

**Comment by coleifer** [comment]
I will re-iterate. Huey uses UTC internally by default, but it assumes that **if you pass it a naive datetime, then that is in localtime**. What is happening internally is you are passing it a naive UTC timestamp, which huey assumes is localtime, so it is converting that to +5 hours.

The reason your task is executed in 5 seconds when you specify `datetime.now()` is because your application code and your consumer are both running in EST. Huey is using UTC internally (which you can see by the 5-hour difference between the logger timestamp and the timestamps huey itself is logging) but when you pass it a naive datetime, it will assume that is localtime and will apply a conversion to UTC.

This is why I suggested:

if you have a requirement of running your code on a server in Eastern time **and** you want to deal with UTC datetimes, then you should probably use tz-aware datetimes in UTC.

**Comment by VijayStroup** [comment]
Oh okay; that makes sense. Sorry I did not understand on your initial response. Thank you very much for the help! 

Great library btw.
