### ISSUE TITLE
Delaying / Blocking Huey task based on condition?

### ISSUE THREAD

**Issue by alnikolaj** [coleifer/huey#579]
Hello, 

I apologise in advance if this question is out of the scope of Huey or not relevant. Is it possible to delay or block a task based on a condition? Basically, similar to a For Loop with a nested While Loop.

I want to use WebSockets in combination with Huey (or a task queue in general). WebSockets to stream data without the need to refresh the website and Huey to send data to the consumer (in my case, I am using Django Channels).

My goal to load a list of objects that shall be delivered to the consumer individually and sequentially, yielding the next item based on a condition. 

E.g. I have a 5 objects loaded from the Database = [Obj. 1, Obj. 2, Obj. 3, Obj. 4]. Huey delivers Obj 1. and halts till a condition is met, such as that Obj 1.status = completed. if this is the case, Huey delivers Obj. 2. and halts again until Obj 2.status = completed, etc. 

Is this possible? 

Thank you in advance!

**Comment by coleifer** [comment]
This is more of a use-case for threads/greenlets/async coroutines and not really an out-of-process task queue. If you used a task for this, the task worked would presumably be tied up the entire time it's waiting, and you would also need a secondary medium for transmitting messages from huey to the websocket, since you can't pass a socket to huey.
