### ISSUE TITLE
Task pipeline without passing results

### ISSUE THREAD

**Issue by radusuciu** [coleifer/huey#607]
Hi, thanks for the great library! This is a feature requests of sorts - unless I've missed something in my reading of the excellent docs.

I'm trying to create a pipeline using the `then` method, but as stated in the docs, this passes task returns results from one part of the pipeline to the other. In my case, although my tasks depend on each other, they do not require the return values from previous tasks. I like having return values for each individual task which capture `stdout` and `stderr` (lots of `subprocess` calls) - perhaps this is something you'd advise against?

Would this be something you'd consider in the scope of the project? It could be a new method, or perhaps a keyword argument on `then`?

Thanks again!

**Comment by coleifer** [comment]
If your task returns *either* `None` or `()` (empty tuple) then nothing is appended to the args. So that is one option. Another consideration is: if the tasks are not communicating in some meaningful way, does this really need to be a pipeline?

Lastly, you can approach this w/just reorganizing your python code a little bit:

* write a wrapper function that delegates to the function that does the work, then returns `None`
* OR, write a task function that calls each function sequentially

```python

@huey.task()
def your_task_a():
    ...

@huey.task()
def your_task_b():
    ...

@huey.task()
def wrapper_task():
    your_task_a.call_local()  # Call the functions synchronously
    your_task_b.call_local()
```

**Comment by radusuciu** [comment]
Thank you for the detailed answer - much appreciated!

Yes, I suppose you're right about the need to make it a "pipeline". In my case, the important part is that things are run in sequence.
