### ISSUE TITLE
[Question] Is it a good idea to separate the redis db number so that one is dedicated to broker/queue and another is for storing tasks results?

### ISSUE THREAD

**Issue by simkimsia** [coleifer/huey#636]
I read that it's a good idea to have 1 redis database for 

- the broker/queue `db 0`
- the result storage `db 1`
- and maybe for django cache `db 2`

Putting aside the django cache, it doesn't seem like huey caters for splitting the redis where there's one for the result storage and one for the broker/queue?

Is my understanding correct?

**Comment by coleifer** [comment]
I am not sure what tangible benefit you would get from this. However, if you want to do this, you will probably need to subclass the `RedisStorage` implementation, because the `db` is only specified:

* When the redis connection is created, or
* Explicitly calling `select()`, in which case it is set for the lifetime of the connection.

So you'd probably be looking at either:

* 2 separate Redis connections, one for the queue/schedule, and one for the result store
* Explicitly calling SELECT before every command (probably a bad idea).

**Comment by simkimsia** [comment]
> I am not sure what tangible benefit you would get from this.

I am not too sure myself tho I read about that for using celery and redis for both queue and result storage purposes.

Just wanted to check. 

Thank you!
