### ISSUE TITLE
is this to replace Celery

### ISSUE THREAD

**Issue by abshkd** [coleifer/huey#64]
that was just a discussion opener. :) I am back to follow all of Charles projects and add them to my toolkit.

**Comment by sdobbelaere** [comment]
> When I wrote huey, which was some time ago, it was partly in response to what I perceived to be the extreme complexity of `celery`. Before 3.0, celery had lots of dependencies and required lots of configuration.
> 
> Huey differs from celery in that:
> 
> * Less dependencies
> * Less configuration
> * Threaded model as opposed to multi-process
> * Less features
> 
> I designed huey for people who need a task queue for simple things like:
> 
> * sending emails
> * generating thumbnails
> * making API calls
> * checking spam
> 
> If you have any of the following needs, then celery is probably a better choice for you:
> 
> * CPU-bound tasks.
> * Distribute tasks to multiple processes, possibly on multiple hosts.
> * Dedicate particular workers to particular tasks.
> * Sophisticated workflows.
> * Auto-scaling and built-in rate-limiting.

Wondering what you would write here 10 years later? @coleifer

**Comment by coleifer** [comment]
I'd write celery, more like smellery.

Seriously though I don't know what all has changed in celery over the years (or the other popular projects in this space). huey's gotten better at a few things since I wrote that, though, so I can write about that. Over the years, Huey's added:

* different worker types, so it can handle a variety of workloads
* priorities
* locking
* pipelines/chaining tasks
* signalling / much more powerful hooks for extending and introspecting huey
* controllable shutdown behavior - graceful or hard
* additional storage backends for different types of deployments

Things huey is not great for:

* at-least-once tasks (we are at-most-once as it is simpler)
* complex pipelines / airflow-type stuff
* monitoring tooling / etc is not on the level of celery ecosystem

huey still remains stupid simple to get going with and can go rather far. I think the users who like huey like it quite well, and that's what I'm going for here.

**Comment by sdobbelaere** [comment]
Personally been using it for probably about 7 years and in all honesty a big fan!

**Comment by coleifer** [comment]
My cat is still just as much of a clown, except now he's got 3 kids bugging him all the time.

![2024-05-09 19 49 26](https://github.com/coleifer/huey/assets/119974/5f85ef8f-060d-48dc-9b8e-2e68a0c59559)

**Comment by sdobbelaere** [comment]
The cat has 3 kids bugging him, ...., or you have 3 kids bugging the cat? 😎
