### ISSUE TITLE
Best practice: Worker is never closing connection to SqliteHuey

### ISSUE THREAD

**Issue by rsirres** [coleifer/huey#676]
Hi,

I use `SqliteHuey` in a flask project. One can see that the `wal` files exists as soon as one creates a task or the `huey_consumer` is running.

This happens because the `producer`(in my case the Flask app) or `consumer` (worker) keep the `sqlite` connection open.

**Problem**: When you create many tasks the `wal` file will get very large without the chance for `huey` to clean up as no (sqlite) checkpoint can happen.

**Question**: Why do we keep the connection open to sqlite ? (on producer as well as consumer side)

**Comment by coleifer** [comment]
>By default, SQLite will automatically checkpoint whenever a [COMMIT](https://sqlite.org/lang_transaction.html) occurs that causes the WAL file to be 1000 pages or more in size, or when the last database connection on a database file closes. The default configuration is intended to work well for most applications. But programs that want more control can force a checkpoint using the [wal_checkpoint pragma](https://sqlite.org/pragma.html#pragma_wal_checkpoint) or by calling the [sqlite3_wal_checkpoint()](https://sqlite.org/c3ref/wal_checkpoint.html) C interface.

Possibly there may be an uncommitted read transaction open that is preventing the WAL from being automatically checkpointed. As far as I can tell, though, just having an open connection should not prevent the WAL from being checkpointed.

You might try editing `huey/storage.py` on ~line 668 and see if this makes any difference (I don't know whether it will since we should be running sqlite in autocommit mode, but it might shed light on whether there are open read txns hanging around):

```python
# Original
def sql(self, query, params=None, commit=False, results=False):

# New:
def sql(self, query, params=None, commit=True, results=False):
```

You can also try changing the journal mode when initializing your huey instance:

```
huey = SqliteHuey(..., journal_mode='delete')
```

Lastly, you can try subclassing or extending the `SqliteStorage` and overriding the `def db(self, ...)` context manager so that it always closes the connection.
