### ISSUE TITLE
Scaling Huey Worker nodes

### ISSUE THREAD

**Issue by Curiouspaul1** [coleifer/huey#677]
Hi, @coleifer hope you're doing great!. Huge fan of your works. I just have a question about scaling a Huey application. I'm quite new to the tool, so pardon my errors, but is it possible to dynamically scale the number of worker threads/processes/greenlets?, based on, like, the amount of traffic. What's the best way to accomplish something like this, without using something like k8s.

I read in the docs, that you can do something like:

```bash
huey_consumer.py my.app.huey -l /var/log/app.huey.log -w 8 -q
```

But instead of doing this beforehand, can I increase the number, as the workload increases too. Also is there a guide I can look at to see what the difference between using threads, and processes and greenlets is? I am running some long-running operations with the consumer tasks, (i think they're not too intensive, just a bunch of external API calls and small calculations back and forth, but long-running nonetheless) so I currently use threaded workers for these. I don't know if using processes would be better or greenlets, however, I would like to have a situation where I can run multiple hundreds or thousands of these simultaneously, that's my end goal.

These are my questions, hope to hear from you soon. Thanks

**Comment by coleifer** [comment]
>but is it possible to dynamically scale the number of worker threads/processes/greenlets

Not really, no. You should probably run a worker-per-core if you expect the workers to be busy. Scaling horizontally can be accomplished by running additional consumer processes (again with worker per core, assuming you're using threads or processes).

>what the difference between using threads, and processes and greenlets is

processes give you access to all the CPU cores on your machine. threads, because of the global interpreter lock, can only occupy a single CPU, and are best for mixed loads of IO and compute. greenlets are good for IO-heavy operations where you potentially want to run a lot of them (sending emails, scraping, e.g.).

> I would like to have a situation where I can run multiple hundreds or thousands of these simultaneously

Bro, I...

**Comment by Curiouspaul1** [comment]
Thanks a lot for responding to my message bro!, i appreciate it. I will surely look up these things up
