### ISSUE TITLE
Feature request: max_concurrent as a task decorator option

### ISSUE THREAD

**Issue by AnthonyGaruccio** [coleifer/huey#683]
Would it be possible to add support for something like this

```python
@task(max_concurrent=5)
def hit_overwhelmable_service(*args, **kwargs):
```
that would result in only a maximum of 5 workers executing instances of that task at any one time?

We have a Django application that uses Huey to run async tasks that contact other web services.  Sometimes these web services are easily overwhelmed with the incoming volume of requests we are submitting to them.  Since the number of workers is a constant shared across all tasks, the only way I can think to remedy this would be to run two instances of Huey with separate queues to restrict the number of workers executing tasks that overwhelm their underlying systems while leaving a larger number of workers for the other tasks.  But, that seems less than ideal.

I would be happy to submit a pull request to add this if you can provide a little guidance!

My initial thought would be to use a redis counter to store the current number of any `max_concurrent`-limited tasks being executed.  Then when another worker grabs an instance of that task from the task-queue, check the value of that counter and compare it to the value of `max_concurrent`.  If it's less, INCR the counter and execute the task.  If it's greater than or equal to `max_concurrent` push the task into a new holding LIST, then grab another task off the main queue.

When a worker finishes a `max_concurrency`-limited task, it first checks to see if the holding-list is empty.  If the holding-LIST is not empty, work the task from the holding list next (without modifying the counter).  Otherwise, decrement the counter and go back to grabbing work from the main queue.

ps: Huey is absolutely great and we love it! Thank you so much for creating it!

**Comment by coleifer** [comment]
This is far too many moving parts for my taste, and all that extra state needs logic to handle restarts/etc. I'd suggest instead doing something easy like storing your "last polled" timestamp, and inside the task check if it's too recent, and if so reschedule the request for later using .schedule()

**Comment by radusuciu** [comment]
I also am interested in functionality like this for similar reasons. Having multiple queues is also not desirable in my case because enqueueing pipelines across queues [has some issues, at least as implemented in `django-huey`](https://github.com/gaiacoop/django-huey/issues/14).

However, I think the suggested implementation could be simpler. I think you could use a redis lock, and if the task is locked due to `max_concurrency` being hit, then you can re-schedule with some delay. This may also remove the need for any extra state logic.

**Comment by coleifer** [comment]
You might take a look at https://github.com/coleifer/huey/blob/master/huey/contrib/helpers.py#L40-L69  for inspiration on implementing something like this.

**Comment by radusuciu** [comment]
Since the `delay` argument of `RetryTask` can now be overridden (referenced in https://github.com/coleifer/huey/issues/734, and implemented in:  https://github.com/coleifer/huey/commit/fa999de41273eaaa92a203efcad0c5260d0e2124), perhaps this tweak of [`lock_task_semaphore`](https://github.com/coleifer/huey/blob/00274ce122b5eac618f1f5a0082afd91b50ab0e8/huey/contrib/helpers.py#L40-L69) will do the trick.

For me, this makes more sense for this application because `RetryTask` feels more appropriate than `TaskException` and the number of retries are unlimited - since we want all of these tasks to be done, just not at all at once, and they should be retried every {delay} seconds.

```python
def limit_concurrency(huey, lock_name, max_concurrency=1, delay=60, timeout=None):
    """
    Limits concurrent task invocations (default concurrency = 1), retrying with
    a delay (default = 60) if the task is locked.

    NOTE: no provisions are made for blocking, waiting, or notifying. This is
    just a lock which can be acquired a configurable number of times.

    Example:

    # Allow up to 3 workers to run this task concurrently. If the task is
    # locked, continue retrying with a delay of 60s, and a timeout of 3600s.
    @huey.task()
    @limit_concurrency(huey, 'my-lock', 3, delay=60, timeout=3600)
    def my_task():
        ...
    """
    sem = RedisSemaphore(huey, lock_name, max_concurrency, timeout)
    def decorator(fn):
        @wraps(fn)
        def inner(*args, **kwargs):
            tid = sem.acquire()
            if tid is None:
                raise RetryTask('task at max concurrency limit, lock: %s' %
                                lock_name,
                                delay=delay)
            try:
                return fn(*args, **kwargs)
            finally:
                sem.release(tid)
        return inner
    return decorator
```
