### ISSUE TITLE
Allow specifying signals directly on task

### ISSUE THREAD

**Issue by yaaminu** [coleifer/huey#684]
#### Problem 
Currently, huey allows users to specify singal that gets executed when a task completes but as it stands that can only be done globally. This means if I just want to perform an action when some specific tasks completes, there's no way to say this signal should only be invoked for this task. The user has to do `if-else` checks inside the signal (see code snippet below). This is wasteful, cumbersome and more importantly prone to mistakes. 

```python
@signal(
   #... signals
)
def foo(signal, task, exc=None):
    if task.name == "task1":
       # do something... 
    elif task.name == "task2":
       # do somethign else
    #more code
```

#### Suggestion
Add a new api for specifying a signal directly inside the @task and all its analogs (see code snippet below). The signal would receive the completion reason which would be one of the existing signals we allowed to specify in `@signal` decorators. 

```python

def on_import_products_complete(completion_reason, **task_args):
     #.. do some set up work depending on completion reason. 

@db_task(...args, signal=on_products_import_complete)
def import_products(...)
    # ... do something 
```

I'm creating this issue because I haven't seen this mentioned inside the docs for (`@signal`, `@task`, `@dbtask`, `@periodic_task`). I can submit a PR to add this feature it it sounds like a good idea. TY!

**Comment by coleifer** [comment]
The API you suggest does not really correspond to any of the existing signals (e.g. there is no signal that emits a "completion reason"). Additionally signals are global to all tasks, because they correspond to events performed by the consumer. If you want to do something when a single task finishes, there's absolutely no reason to use a signal. Just use a regular decorator.

```python
def on_import_products_complete(fn):
    @functools.wraps(fn)
    def decorator(completion_reason, ...):
         # do some work depending on completion reason.
    return decorator

def import_products(...):
    # do the import.

import_products_task = db_task(on_import_products_complete(import_products))
```

Rather than implement something like this, I would suggest that you can write your own set of decorators instead.
