### ISSUE TITLE
Huey blocks forever with store_none=False, blocking=True

### ISSUE THREAD

**Issue by jamesob** [coleifer/huey#688]
The following (pseudo-code) will block forever, which I think is a little surprising.

```
h = RedisHuey('name', url='...')

@h.task()
def some_task():
    do_thing()
    return None

r = some_task()
r(blocking=True)
```

The tricky interaction here is that the task returns None, and Huey is by default configured for `store_none=False`. When we call the result with `blocking=True`, we're waiting for a non-`EmptyResult` value which never comes.

I think this behavior is okay, it's just a little surprising that it happens with defaults. I think this would be hard for Huey to detect, since it would need to inspect the return type of the task function... so maybe we can add something to the docs? Any better ideas @coleifer?

**Comment by coleifer** [comment]
Yeah, this is expected (if somewhat surprising) behavior - tasks should always have a non-None return value if you expect to block on their result w/`store_none=False`. We don't store `None` by default because it could quickly overwhelm the result store's memory if you execute lots of tasks and don't care about the result. On the flip-side, any non-None result gets put into the result store, and it's expected/hygienic in those cases to read those results or use a storage that automatically expires stale results. So `None` is a bit overloaded, but it's all for the purpose of keeping the result store size manageable and predictable.

**Comment by jamesob** [comment]
I'll put up a PR for an explanation in the docs soon. Thanks for the quick response!
