### ISSUE TITLE
Release memory after periodic task

### ISSUE THREAD

**Issue by jacksongoode** [coleifer/huey#704]
I currently run a job that imports some big libraries for machine learning to generate a doc every couple hours.

```python
@huey.periodic_task(crontab(minute=0, hour="*/4"))
def cron_gen_bert():
    model, topic_docs, news = generate_bert()

    # Cleanup?
    del model, topic_docs, news
    del sys.modules['bertopic']
    del sys.modules['sklearn']
    gc.collect()
 ```
 
However, this task acquires ~500mb of memory and doesn't dispose it afterwards. I'm wondering if this is expected behavior or if there is someway to decouple the import libraries from the main thread of the process (FastAPI). It's mostly a question to cut costs for the cloud provider that bills by the amount of memory occupied over time.

Edit: Maybe this is a task for MiniHuey... I'll try this!

**Comment by coleifer** [comment]
I don't believe this is huey-specific and can't really suggest a solution other than what you've already implemented (deleting the objects and calling gc collect). I'd suggest profiling with a memory profiler to see where the issue may lie.

Worst case you can make this into a standalone python script and "she'll out" to it from your Huey task?

**Comment by jacksongoode** [comment]
Hmm, okay I'll try this. Am I wrong to assume that libraries imported within the scope of the huey task wouldn't be disposed of (in a separate process)?

**Comment by coleifer** [comment]
I'm not sure I understand your question, but I will try to explain my answer.

You really don't have much control over what memory is allocated and used by Python, especially when it comes to libraries. Maybe it sticks around, maybe it doesn't - but it's not necessarily anything to do with Huey. Huey is just regular python that runs your code.

My suggestion was to have your task shell out to a separate process so that the OS could do all the cleanup after it finished, e.g.:

```
# tasks.py
@huey.periodic_task(crontab(minute=0, hour="*/4"))
def cron_gen_bert():
    import subprocess
    p = subprocess.Popen(['python', 'generate_bert.py'], stdout=subprocess.PIPE)
    p.communicate()

# Separate file "generate_bert.py":
if __name__ == '__main__':
    model, topic_docs, news = generate_bert()
    etc.
```

This way the memory used by the consumer will not be affected by the libraries. But it's just a suggestion. I'm not sure if the memory is growing every time you run or if it stays steady? Also, minihuey is not designed for this - minihuey is for green-threaded applications.
