### ISSUE TITLE
 OperationalError : 2006, 'MySQL server has gone away'

### ISSUE THREAD

**Issue by Skrattoune** [coleifer/huey#711]
Hi, 
I regularly have tasks that take more than 10h to execute.
beyond a certain duration, the MySQL server times out and closes the connection, leading to an error `OperationalError : 2006, 'MySQL server has gone away'`.

after many deep enquires, it seems the connection is reset when the task is started, then after the task is completed:

cf `venv\Lib\site-packages\huey\contrib\djhuey\__init__.py`:

```
def close_db(fn):
    """Decorator to be used with tasks that may operate on the database."""
    @wraps(fn)
    def inner(*args, **kwargs):
        if not HUEY.immediate:
            close_old_connections()
        try:
            return fn(*args, **kwargs)
        finally:
            if not HUEY.immediate:
                close_old_connections()
    return inner


def db_task(*args, **kwargs):
    def decorator(fn):
        ret = task(*args, **kwargs)(close_db(fn))
        ret.call_local = fn
        return ret
    return decorator
```

What can I do to avoid this error to happen ?

Is it safe to put somewhere in my task code a reset of the connection (`close_old_connections()`) ?
Or how should I proceed?

Thanks for advising me, because I have no clue about db connection persistence, and what is the interraction with `django huey`.

**Comment by coleifer** [comment]
This is absolutely not a huey issue. Your MySQL server is configured to kill idle connections, which a quick search on google would have made clear: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout

If anything, Huey is attempting to avert such a situation by ensuring the connection is opened and closed cleanly.

You will need to either:

1. occasionally ping your mysql connection during these long idle periods
2. explicitly manage transactions/connections yourself within the task
3. set a larger `wait_timeout` for your session at the beginning of the task or globally

**Comment by Skrattoune** [comment]
Thanks for your quick feedback.

> This is absolutely not a huey issue. Your MySQL server is configured to kill idle connections, which a quick search on google would have made clear: [dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout)

This was indeed very clear to me :-)

I'll look deeper into how I could implement your two recommandations:

> * occasionally ping your mysql connection during these long idle periods
> * explicitly manage transactions/connections yourself within the task

**Comment by ProNatanSLVDR** [comment]
Hi everyone, 
In my context (django) i got the same error because i wasnt running my tasks properly.
It lead me to this issue, so ill explain the fix here.

For anyone getting this error : 
`django.db.utils.OperationalError: (2006, 'Server has gone away')`

Its because django doesnt close the connexion to the db when running a task, then after a long time, you db closes the connexion and thats why you get the error.

To fix this the easy method is to replace your decorator :
`@task`

with :
`@db_task`

This will ensure connexion to db is closed after your task ends, then reopened the next time your task is launched (instead of trying to keep it alive until next task).

The link to the documentation that covers this :
https://huey.readthedocs.io/en/latest/contrib.html#tasks-that-execute-queries

@coleifer (thx for your work !) Maybe specify this on the django section of the docs ? im not sure but it could help
