### ISSUE TITLE
Handling of failed tasks

### ISSUE THREAD

**Issue by spapas** [coleifer/huey#718]
I'd like to discuss the handling of failed tasks if I may. Let's suppose I wanna send an email so I create a send email task like this: 

```python 
@huey.task(retries=5, retry_delay=60)
send_email(subject, body, to):
  [...]
```

The above task will be retried 5 times but what happens if it fails every time? Will the email get lost ?

Is there a way to handle the tasks that are failed and have no retries? I didn't see anything about that in the docs. What do other people doing? Should I architecture my tasks in such a way so as to *not* get lost ? How?

**Comment by coleifer** [comment]
When you enqueue a task by calling the wrapped function, e.g. `r = send_email(...)`, then `r` is your result handle. This handle allows you to access the result of running the task after the consumer executes it - similarly, if the task failed with an exception, the result handle will raise an exception if you resolve it. When a task fails and is retried (because you specified 1 or more `retries`) then the result handle can continue to be used to check on the results of the retries. So that is one way -- you can use the result handle to see if the task failed or not.

You can alternatively add a [signal handler](https://huey.readthedocs.io/en/latest/signals.html) so that if a task failed with an unhandled exception, your signal handler will be invoked. This is easiest if you don't want to keep a result handle around and blocking on resolving it / etc.

Ultimately this is the nature of an asynchronous task queue... You will have to decide how to handle them. Your errors don't disappear into a black hole - they are observable via the result handle, stored in the result store itself, and visible to signal handlers. They are also logged, so you can attach a custom log handler as well.

**Comment by spapas** [comment]
Hello @coleifer thank you for the thourough answer. I mainly want to use the tasks in a request/repsonse cycle from a django web app so I can't really save the response for using/checking it later. 

I took a peek at the signals and saw a `SIGNAL_ERROR` and a `SIGNAL_RETRYING`, however there's no `SIGNAL_ERROR_NO_RETRIES` i.e a way to get signals of tasks that have failed and won't be retried. Am I missing something ? 

I guess I could skip retrying and handle all tasks that error out?

**Comment by coleifer** [comment]
Signal handlers are called with the task instance so you can add an error handler and check the task instances `task.retries` attribute.

**Comment by spapas** [comment]
Excellent ! Thank you for clarifying
