### ISSUE TITLE
Can huey deploy multiple instance？

### ISSUE THREAD

**Issue by hbxcyz1** [coleifer/huey#724]
Hey,

Can huey deploy multiple instances？

If possible, can you please provide a guide for me？

like this,
docker container1:  huey_consumer tasks.huey -w 16
docker container2:  huey_consumer tasks.huey -w 16
docker container3:  huey_consumer tasks.huey -w 16
……
Periodic tasks and asynchronous tasks are random execute on different machines, and the tasks will not be excuted repeatly.

**Comment by coleifer** [comment]
You can do this, sure. The main thing is to ensure that only one consumer is set to enqueue periodic tasks. Otherwise you'll see your periodic tasks getting enqueued multiple times. To accomplish this you would run *all consumers except one* with the "-n" option.

https://huey.readthedocs.io/en/latest/consumer.html#options-for-the-consumer
