### ISSUE TITLE
How to revoke dynamically created tasks?

### ISSUE THREAD

**Issue by rtu-dataframe** [coleifer/huey#729]
Hi, i'm trying to create a bunch of dynamic scheduled tasks, actually i'm using the example reported in docs:
```

def dynamic_ptask(message):
    print('dynamically-created periodic task: "%s"' % message)

@huey.task()
def schedule_message(message, cron_minutes, cron_hours='*'):
    # Create a new function that represents the application
    # of the "dynamic_ptask" with the provided message.
    def wrapper():
        dynamic_ptask(message)

    # The schedule that was specified for this task.
    schedule = crontab(cron_minutes, cron_hours)

    # Need to provide a unique name for the task. There are any number of
    # ways you can do this -- based on the arguments, etc. -- but for our
    # example we'll just use the time at which it was declared.
    task_name = 'dynamic_ptask_%s' % int(time.time())

    huey.periodic_task(schedule, name=task_name)(wrapper)
```

Everything works fine, but i need to delete (revoke) some of those tasks based on user interaction.

I've tried to get the `task_class` from inside the `schedule_message` function as reported below, but nothing, i'm getting only None values:

`HUEY_SCHEDULED_TASKS.append(huey.periodic_task(schedule, name=task_name)(wrapper).task_class)`

My goal is to use` huey.revoke_all()` method in order to revoke all instance task based on class

Fyi, `HUEY_SCHEDULED_TASKS` is a list that keep track of the scheduled tasks.

Anyway, i've tried everything but i'm unable to figure out how to delete (revoke) one dynamically created scheduled message: you could please give me some advices?

Many Thanks

**Comment by coleifer** [comment]
Since the `schedule_message` runs within the context of the consumer, it is only visible to the workers and not the application/caller -- not sure if that makes sense to you, but I'm going to assume it does. Additionally it will only work when using threaded workers -- processes will not be able to see one anothers memory.

At any rate, I made the following example, which seems to work just fine with threaded workers:

```python
TASKS = []

def dynamic_ptask(msg):
    print('dynamically-created periodic task: %s' % msg)
    print('(dynamic tasks: %s)' % TASKS)

@huey.task()
def schedule_message(message, minutes):
    def wrapper():
        dynamic_ptask(message)

    schedule = crontab(minutes)
    task_name = 'dynamic_ptask_%s' % int(time.time())
    w = huey.periodic_task(schedule, name=task_name)(wrapper)
    TASKS.append(w.task_class)
```

If I then run the consumer with the above task and open a shell and run the following:

```
schedule_message('every 2 minutes', '*/2')
schedule_message('every minute', '*')
```

At 11:35 I see the consumer output:

```
11:35:15 Executing tasks.dynamic_ptask_1680194073: 80efd213-16dc-4fc5-a70f-a4dea8b1d10f
dynamically-created periodic task: every minute
(dynamic tasks: [<class 'tasks.dynamic_ptask_1680194066'>, <class 'tasks.dynamic_ptask_1680194073'>])
```

You can see that, from the workers perspective, there are two dynamically-created periodic tasks present in the `TASKS` global.
