### ISSUE TITLE
Possibility of switching to 'spawn' instead of 'fork'?

### ISSUE THREAD

**Issue by heshiming** [coleifer/huey#758]
Hi.

In my experience, Python's multiprocessing works better in 'spawn' method compared to 'fork'. I remember seeing references from developers from large projects saying that 'fork' causes all kinds of problems from memory-leak to performance drag. And everything went away simply via switching to 'spawn'. I can provide some details if you are interested.

But in huey, you seems to be sticking to 'fork'. Like in [this consumer line](https://github.com/coleifer/huey/blob/a8f85f5880645c7fec71277cd1e50455b7321d20/huey/bin/huey_consumer.py#L60C14-L60C14), you switched to 'fork' even though the Mac default has been 'spawn' since Python 3.8, for good reasons. And of course on Linux, you are using the default 'fork'.

I tried to alter the consumer, making it 'spawn' based. Which will lead to a pickle error because [this _run function](https://github.com/coleifer/huey/blob/a8f85f5880645c7fec71277cd1e50455b7321d20/huey/consumer.py#L350) cannot be pickled. Then I tried putting it into global space, which then lead to many other functions being not pickled.

Then I found this line in your [documentation](https://huey.readthedocs.io/en/latest/consumer.html?highlight=windows#worker-types), that states ... 

> `The only process start method available on Windows is “spawn”, which has the downside of requiring the Huey state to be pickled. Huey uses (and creates) many objects which cannot be pickled.`

Which unfortunately seems like a design problem in the end. Now that I understand your consumer imports are relying on 'fork', how hard it is to provide a 'spawn' option for this library? I mean just an overview, how many things have to be changed?

Thanks!

**Comment by coleifer** [comment]
`spawn` doesn't work, and honestly seems like a kludge because it requires completely serializing the entire interpreter state (via pickle) and copying it into a new process. `fork` works well for us because there are frequently, in huey applications, things that may not be pickle-able (e.g. Redis instances) -- this includes huey tasks as well.

>I remember seeing references from developers from large projects saying that 'fork' causes all kinds of problems from memory-leak to performance drag

This sounds like hearsay, fud and nonsense to me. `fork` is a standard unix system call. If anything is problematic, I'd say it is requiring pickle to serialize the state of the interpreter.
