### ISSUE TITLE
Better documentation for dynamic periodic tasks

### ISSUE THREAD

**Issue by sixhobbits** [coleifer/huey#761]
Huey has an example of using [dynamic periodic tasks](https://huey.readthedocs.io/en/latest/guide.html#dynamic-periodic-tasks) with arguments in the guide, but there doesn't seem to be documentation about how to manage these tasks. It's also confusing that the main periodic task docs say that it isn't possible to pass arguments to periodic tasks, even though that is done in the dynamic example.

My main questions that I can't find easy answers to include:

* **Where are dynamic periodic tasks stored?** I'm using sqlite and I don't see them anywhere in the database (`select * from tasks` `select * from schedule` and `select * from kv` doesn't show anything related to these, and those are the only tables I have) and `huey.read_schedule()` or `huey.read_periodic(None)` also show empty lists, even when I have dynamic periodic tasks scheduled.
* **How do I cancel or revoke specific dynamic periodic tasks?** If I try to call revoke on the wrapper function it just stops me from scheduling new tasks, but I can't find a way to revoke specific scheduled tasks, even though I am giving each one a unique name.
* **How do I persist periodic tasks across restarting the consumer?** If I restart the consumer I lose all the dynamic periodic tasks. Is there a way to persist them across consumer restarts? 

Maybe this is out of scope for Huey, or my difficulties are just because I don't have a good understanding of how Huey works, but if you have any information about this I'd be happy to make a PR to the guide or docs to help others too.

For context, I'm using Huey as part of an AI Telegram Chatbot. At the moment each user message becomes a huey task that calls different functions (for 'remind' tasks, 'web scraping' tasks, and some others), but I'd also like the user to be able to do things like "send me the headlines from CNN every morning at 9am", which is what I'm trying to use dynamic periodic tasks for.

**Comment by coleifer** [comment]
>Where are dynamic periodic tasks stored.

This is answered in the very first paragraph of the docs you linked...

>To create periodic tasks dynamically we need to register them so that they are added to the in-memory schedule managed by the consumer’s scheduler thread. Since this registry is in-memory, any dynamically defined tasks must be registered within the process that will ultimately schedule them: the consumer.

It is not possible to pass arguments to periodic tasks.

>I don't have a good understanding of how Huey works

Yes... to use dynamic periodic tasks you should absolutely understand how Huey works in-and-out because there are lots of gotcha's.

-------------------------------------------

I'm going to skip trying to answer your other questions and just say this... Just about every single time someone asks for dynamic periodic tasks, they are someone with not very much experience or understanding of how this tooling works. They think they've stumbled on some magic recipe that will solve all their problems without realizing that they've simply pushed their problem into a harder place to manage.

The correct way to do what you're asking about, in my opinion, is to persist the user schedules in the database like you would normally. e.g.:

* User 1: 9am cnn headlines
* User 1: 9pm bbc headlines
* User 2: ...
* User 3: ...

Then run a **single** periodic task every 15 minutes or every hour -- whatever the minimum granularity you want to allow your users to schedule things.

When that single periodic task runs, it will check all the user schedules for the current time and process them. It can delegate to sub-tasks, alternatively, e.g.:

```python
@huey.periodic_task(crontab(minute='0'))  # Run every hour, on the hour.
def schedule_messages():
    now = datetime.datetime.now()
    for user_schedule in UserSchedule.get_list_for_time(now):
        fetch_user_schedule(user_schedule)

@huey.task()
def fetch_user_schedule(user_schedule):
    # ... fetch headlines or whatever ..
```

When a user wants to created, edit, or delete their schedule all you need to do is modify the database table. No need to use dynamic periodic tasks.
