### ISSUE TITLE
Task not using Django database user.

### ISSUE THREAD

**Issue by edmundrotimi** [coleifer/huey#799]
I am trying to run huey, precisely django_huey, but each time I perform a Django query in the background task, 'root' is used as the user for the DB. Other parts of the application work well with the database config in Django settings, like migration, etc.

    [program:application]
    directory=/home/.../django_project
    command=/home/.../.cache/pypoetry/virtualenvs/..../bin/python /home/.../.../manage.py djangohuey --queue application
    user='...'
    autostart=true
    autorestart=true
    redirect_stderr = true                                               
    stdout_logfile = /etc/supervisor/realtime.log
    environment=PATH="/home/.../.../lib/python3.12/site-packages"
    stopwaitsecs=30

    # task
    @db_periodic_task(crontab(minute='*/1'), queue='application')
    def app_task():
        # current date and time
        current_timestamp = timezone.localtime(timezone.now())

        # get all event
        get_events = Mymodel.objects.order_by('-creation_time').filter(
            time_ends__lt=current_timestamp
        )

        if get_events.exists():
            ...
Error: connection failed: connection to the server at "127.0.0.1", port 5432 failed: FATAL: password authentication failed for user "root". This error occurs only in the task in production, but every other aspect of the application works smoothly with the database config in the settings.

**Comment by coleifer** [comment]
I think I already made it clear in #798 that whatever the issue is, it is not Huey. You probably need to specify your database configuration in your settings file.

Also I don't have a clue what `djangohuey` is, that is not a project I operate. Huey already comes with a management command, but it is `manage.py run_huey`.

Please take it up with the maintainer here: https://github.com/gaiacoop/django-huey
