### ISSUE TITLE
Create a signal for when a task is enqueued

### ISSUE THREAD

**Issue by milenb17** [coleifer/huey#821]
I want to be able to monitor how long tasks are waiting in a queue, so it would be helpful to have a signal that is sent when a task is enqueued.

**Comment by coleifer** [comment]
See https://github.com/coleifer/huey/issues/581 - tldr is write / wrap your own `task()` decorator that does what you want when a task is enqueued. You can also override `Huey.enqueue`.

Signals are executed within the scope of the consumer. Tasks are not necessarily enqueued there. That is why the signals for enqueue are not exposed.

**Comment by wedens** [comment]
Is there a way to do that for periodic tasks, since huey itself enqueues them? My use case is that I have tasks that can be executed periodically or triggered manually and I want to prevent the manual triggering when a task is already enqueued or running. I can handle the "running" state myself, but I don't see a way to check whether a periodic task is enqueued or not.
