### ISSUE TITLE
consumer: disabling periodic tasks doesn't prevent scheduler sleep loop

### ISSUE THREAD

**Issue by tboddyspargo** [coleifer/huey#827]
This is a relatively minor thing, but we noticed that the scheduler worker still blocks for the schedule-interval duration even if the consumer is running with `--no-periodic`. The impact is that the process termination after SIGINT might be delayed up to the `scheduler-interval` even when the consumer is "idle".

It might be nice to avoid blocking that worker if periodic tasks or scheduler tasks are disabled.

Another option would be to have a thread-safe `Event` that you `wait` on for the scheduler interval and can be set by the signal handlers to exit the loop early if a shutdown has been requested.

**Comment by coleifer** [comment]
>or scheduler tasks are disabled.

Yeah that's the catch, we don't want to disable scheduled tasks altogether. The default scheduler interval is 1s, so I'm not really sure how much fat there really is to trim here.

>Another option would be to have a thread-safe Event that you wait on for the scheduler interval and can be set by the signal handlers to exit the loop early if a shutdown has been requested.

Sure, that would probably work, but also note that Huey workers may be "polling" rather than "blocking", and so they may sleep as well depending on the storage implementation you are using.

All-in-all, I think the current behavior is acceptable.

**Comment by tboddyspargo** [comment]
Thanks for considering!

> The default scheduler interval is 1s, so I'm not really sure how much fat there really is to trim here.

It just grows more painful for people that start to customize with longer `scheduler-interval` values. I might want to have the scheduler run every 60s, but it's painful for that to mean that the process might not exit for up to 60s after `SIGINT` was sent even if the container is idle.
