### ISSUE TITLE
PostgresSql storage

### ISSUE THREAD

**Issue by alexandernst** [coleifer/huey#828]
I'm interested in being able to use Huey with Postgres. That would allow me to have a similar experience to Rail's [Solid Queue](https://github.com/rails/solid_queue), aka use a job queue without having to configure/deploy any external dependencies.

I had a quick look at the code (both `SqliteStorage` and the several `RedisStorage*` classes) and I think it should be relatively easy to add a new `PostgresqlStorage`.

If I were to create a PR implementing such a feature, would you be open to merging it? (given that the code complies with your criteria of quality, comments, ideas, suggestions, etc...)

**Comment by coleifer** [comment]
You can just use the `huey.contrib.sql_huey` implementation. It supports Postgres, MySQL or Sqlite and uses peewee. https://github.com/coleifer/huey/blob/master/huey/contrib/sql_huey.py

**Comment by alexandernst** [comment]
I totally missed this and it seems almost like what I'm looking for! I didn't state this in my first comment, but I'm using huey from within a Django project. I was hoping to be able to get some sort of "integration" with Django, such as automatically create the required tables using Django's own ORM/models and use Django's own DB connection. Maybe this could be a good fit for `djhuey`?

**Comment by coleifer** [comment]
Check out https://github.com/gaiacoop/django-huey/tree/main -- found it from a quick google search, looks reasonably up-to-date as well.

**Comment by klausfrandsen** [comment]
After playing around with huey-django-orm for the remainer of yesterday, I've learned quiet a few things that any user want to know:
* Locking in the dequeue() is made with threads, which obviously does not work when running with process_type=process, which is required if your tasks are CPU-heavy (and not just I/O). As a result, task execution can easily be duplicated, and stuff crash left and right.
* For some reason, the priority-field is a DecimalField with a max-value of 10, for no good reason really.

I have a local version that does syncronization via DB locking (select_for_update ORM calls) instead of threads, but I'm not sure I can get it to co-exist with the current version.
